### ISSUE TITLE
[next] Image组件兼容

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#103]
**Is your feature request related to a problem? Please describe.**

在`next`框架下，不使用next提供的`Image`组件用普通的img在生成打包的时候回报error，用了的话好像会有适配的问题，`Image`的`width` `height`属性似乎是行内的，`postcss-pxtorem`不能转换行内样式

**Describe the solution you'd like**
兼容`Image`组件，在生产上不报error

**Comment by 3lang3** [comment]
https://github.com/3lang3/react-vant-template/tree/main/template/nextjs
next demo 是否已经解决？
