### ISSUE TITLE
🐛 [CLI] vant.config.js配置与vant不同

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#110]
**简述bug**
vant.config.js 配置中不存在 locales直接写nav会报错
title 配置与vant不同

**截图**
![image](https://user-images.githubusercontent.com/33956589/137584440-8985b462-11c0-4b2c-a6af-6574e32b9e45.png)

**设备信息:**

**Comment by 3lang3** [comment]
> > @TinsFox 需要支持非locales配置吗？
> 
> 我觉得还是有必要做个兼容的，我就拿`react-vant-cli` 写过文档，虽然没有现有的成熟文档工具功能齐全，但是胜在简单。在`create-react-vant-cli` 创建出来的demo中应该也是没有 locales 的，一般在国内来说多语言还是用的少。
> 
> 除此之外，`react-vant-cli` 构建的文档会不会支持SEO啊 🤪

需要支持seo的话就用nextjs好了，可实现的。
在vant.config.js里面新增`locales: boolean`字段，用于控制是否走国际化

**Comment by 3lang3** [comment]
cli已经移出仓库，采用 [rcdoc](https://github.com/3lang3/rcdoc) 构建
