### ISSUE TITLE
List组件 有个场景外部有几个过滤条件，过滤完后有数据，继续下拉，那不是过滤条件状态无法取到最新的，导致下拉的数据依旧是之前没过滤的状态？

### ISSUE THREAD

**Issue by xiaojingyuaner** [3lang3/react-vant#119]
有个场景外部有几个过滤条件，过滤完后有数据，继续下拉，那不是过滤条件状态无法取到最新的，导致下拉的数据依旧是之前没过滤的状态？

__最初由 @xiaojingyuaner 在 https://github.com/3lang3/react-vant/issues/118#issuecomment-947517518 发布__

**Comment by 3lang3** [comment]
大概明白你意思了 我去写个demo吧
