### ISSUE TITLE
[Dialog] demo 自定义内容 close icon 错位

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#128]
**简述bug**
文档demo中的 自定义内容左上角图标错位

https://3lang3.github.io/react-vant/#/zh-CN/dialog

**截图**
![image](https://user-images.githubusercontent.com/33956589/139646699-f26702e4-7997-4293-a864-c5d2086f8c77.png)

**Comment by 3lang3** [comment]
@TinsFox 方便pr吗？

**Comment by TinsFox** [comment]
> @TinsFox 方便pr吗？

这两周可能没啥空🌚

**Comment by 3lang3** [comment]
👌  那我来吧
