### ISSUE TITLE
⭐️ [Component] Remove React.FC

### ISSUE THREAD

**Issue by lodisy** [3lang3/react-vant#130]
**Is your feature request related to a problem? Please describe.**

React.FC was already deprecated two years ago..

https://github.com/facebook/create-react-app/pull/8177

**Describe the solution you'd like**

Recommend ways like [following](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components/):

```
// Declaring type of props - see "Typing Component Props" for more examples
type AppProps = {
  message: string;
}; /* use `interface` if exporting so that consumers can extend */

// Easiest way to declare a Function Component; return type is inferred.
const App = ({ message }: AppProps) => <div>{message}</div>;

// you can choose annotate the return type so an error is raised if you accidentally return some other type
const App = ({ message }: AppProps): JSX.Element => <div>{message}</div>;

// you can also inline the type declaration; eliminates naming the prop types, but looks repetitive
const App = ({ message }: { message: string }) => <div>{message}</div>;

```

**Describe alternatives you've considered**

**Additional context**

**Comment by 3lang3** [comment]
当前在进行swipe重构，欢迎提类型优化的pr，不需要全部，单个组建的也行😀
