### ISSUE TITLE
Popup组件销毁的时候没有unLockScroll

### ISSUE THREAD

**Issue by AdonLee** [3lang3/react-vant#133]
**简述bug**
Popup组件销毁的时候没有unLockScroll

**预期行为**
Popup组件在销毁时候执行unLockScroll

**Comment by 3lang3** [comment]
@AdonLee 是在外面直接把popup组件销毁的吗？类似下面这种情况？
```jsx
{ bool && <Popup visible={true} /> }
```

**Comment by 3lang3** [comment]
按照上面的代码能复现出来，下次发包会修复掉

**Comment by AdonLee** [comment]
> @AdonLee 是在外面直接把popup组件销毁的吗？类似下面这种情况？
> 
> ```js
> { bool && <Popup visible={true} /> }
> ```

是的
