### ISSUE TITLE
ConfigProvide 使用体验

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#138]
**Is your feature request related to a problem? Please describe.**

使用 `ConfigProvide` 修改组件局部样式的时候需要复制暴露出来的 CSS 变量变量（如下表），但是在定义`ConfigProvide` 参数时，又得使用大驼峰命名。
中横线与大驼峰之间的命名是有什么插件可以自动转吗？现在是复制了中横线然后一个个改大驼峰，感觉有、繁琐。

**使用插件还是组件做一个兼容或者是文档增加大驼峰的变量名上去呢**

```js
const themeVars = {
  rateIconFullColor: '#ffcc56',
  sliderBarHeight: '4px',
  sliderButtonWidth: '20px',
  sliderButtonHeight: '20px',
  sliderActiveBackgroundColor: '#951fff',
  buttonPrimaryBorderColor: '#951fff',
  buttonPrimaryBackgroundColor: '#951fff',
}
```

| 名称                                         | 默认值                                  | 描述 |
| -------------------------------------------- | --------------------------------------- | ---- |
| --rv-dropdown-menu-height                    | _48px_                                  | -    |
| --rv-dropdown-menu-background-color          | _var(--rv-white)_                       | -    |
| --rv-dropdown-menu-box-shadow                | _0 2px 12px fade(var(--rv-gray-7), 12)_ | -    |
| --rv-dropdown-menu-title-font-size           | _15px_                                  | -    |
| --rv-dropdown-menu-title-text-color          | _var(--rv-text-color)_                  | -    |

**Comment by 3lang3** [comment]
体验上确实可以优化
