### ISSUE TITLE
组件BaseTypeProps

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#140]
**简述bug**

组件继承的`BaseTypeProps` 是不是有写组件没有去写使用，图二中的 `style` 没有生效

**截图**
![image](https://user-images.githubusercontent.com/33956589/140030188-1ebed0b4-98ee-4628-9b20-c0093df2424a.png)

![image](https://user-images.githubusercontent.com/33956589/140030452-bc136934-0924-4f18-b991-2d14612db5b4.png)

**Comment by 3lang3** [comment]
DropdownMenu确实没挂上style

**Comment by TinsFox** [comment]
尝试修复 背景色没生效，疑惑.jpg🧐 

![image](https://user-images.githubusercontent.com/33956589/140034309-1d494cf9-f76e-421c-aec0-52107886e9ca.png)

![image](https://user-images.githubusercontent.com/33956589/140034374-5d106fb0-b813-47ee-bb05-6c1dab67b91b.png)

**Comment by 3lang3** [comment]
`rv-dropdown-menu__bar`遮挡了
