### ISSUE TITLE
[List] Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#143]
**简述bug**
文档demo报错，具体见下图

**复现代码**
http://localhost:8080/#/zh-CN/skeleton 文档demo报错

**截图**
![image](https://user-images.githubusercontent.com/33956589/140277878-0307d0b0-1604-4019-917b-7d466e71b6bc.png)

**Comment by 3lang3** [comment]
list的问题，应该是cleanup没处理好
