### ISSUE TITLE
next 下  useLayoutEffect  引发报错

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#144]
**简述bug**
react-vant@1.3.0下 useLayoutEffect 引发了报错，但是奇怪的是在简单的 nextdemo下 不会报错

**复现代码**
提供复现代码片段，极大的提升开源工作效率。

没能在别的项目复现出来😤

**预期行为**
预期行为描述。

**截图**
![image](https://user-images.githubusercontent.com/33956589/140286840-636cfd73-a9c5-47f1-ae9f-e0f1022115df.png)

**Comment by TinsFox** [comment]
初步排查是 `Image` 组件引起的

**Comment by TinsFox** [comment]
`Tabs` 组件也会引起

**Comment by 3lang3** [comment]
明天看下

**Comment by TinsFox** [comment]
复现仓库：https://github.com/TinsFox/next-reavt-vant
复现步骤：
1. `yarn && yarn dev`
2. 访问 `http://localhost:7000/image`
在next下，直接访问 `Image`组件所在的页面会报错，从别的页面过去就不会了

**Comment by 3lang3** [comment]
> 复现仓库：https://github.com/TinsFox/next-reavt-vant 复现步骤：
> 
> 1. `yarn && yarn dev`
> 2. 访问 `http://localhost:7000/image`
>    在next下，直接访问 `Image`组件所在的页面会报错，从别的页面过去就不会了

收到

**Comment by TinsFox** [comment]
复现仓库：https://github.com/TinsFox/next-reavt-vant
复现步骤：
1. `yarn && yarn dev`
2. 访问 `http://localhost:7000/image`
在next下，直接访问 `Image`组件所在的页面会报错，从别的页面过去就不会了
