### ISSUE TITLE
[DropdownMenu] 状态选中 && 默认值

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#146]
**简述bug**
DropdownMenu 已经选中的状态下再次点击不会收起，

**预期行为**
再次点击直接收起会比较符合用户行为

**截图**
![image](https://user-images.githubusercontent.com/33956589/140449020-4625ffc0-c200-4069-b34b-8c6210932739.png)

**Comment by TinsFox** [comment]
默认值 #https://github.com/3lang3/react-vant/issues/137#issuecomment-961580735

**Comment by 3lang3** [comment]
@TinsFox DropdownMenu当前只有受控行为，所以没有defaultValue属性，可以考虑增加。

**Comment by 3lang3** [comment]
> DropdownMenu 已经选中的状态下再次点击不会收起

可以优化
