### ISSUE TITLE
[Search] bug  `onClickInput` 无效

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#149]
**简述bug**

`Search`组件的 `onClickInput` 在搜索框禁用状态(`disabled`)下无响应

**Comment by 3lang3** [comment]
disabled的时候无响应不是应该的吗？

**Comment by TinsFox** [comment]
看淘宝 app的设计是点击输入框的位置后跳转到其他页面的，图标跟按钮都有自己的交互事件。也不是 disabled 之后就没有交互了的呀，不能输入点一下还是应该有反应的

**Comment by 3lang3** [comment]
> 看淘宝 app的设计是点击输入框的位置后跳转到其他页面的，图标跟按钮都有自己的交互事件。也不是 disabled 之后就没有交互了的呀，不能输入点一下还是应该有反应的

哎哟 有点道理
