### ISSUE TITLE
🐛 [CLI] `react-vant-cli create`命令功能异常

### ISSUE THREAD

**Issue by qyjandroid** [3lang3/react-vant#237]
### 🐛 漏洞描述 (Bug description)

react-vant-cli create 命令不能使用

### 🐾 复现步骤 (Steps to reproduce)

react-vant-cli create react-com-libs
![image](https://user-images.githubusercontent.com/6645414/142154676-624a0774-3e16-437a-85bf-2825278505e0.png)

### 🌈 想要的结果 (Desired result)

可以直接创建组件库脚手架

### 📦 环境信息 (Environmental information)

- Device: windows 10
- nodejs: v12.18.4

**Comment by 3lang3** [comment]
朋友试试这个`create-react-vant-cli-app`

**Comment by TinsFox** [comment]
使用`create-react-vant-cli-app` 创建 vant类的react组件库命令为 `npx create-react-vant-cli-app react-vant-npx`
`react-vant-npx` 为工程目录名

**Comment by qyjandroid** [comment]
组件库创建成功了，但是新建一个组件的时候，引入了一些默认的文件找不到，虽然我可以删掉这些文件，但是我还是希望能默认补全这些文件！另外想问一下如果组件中引入图片，图片的位置有要求吗？还是是否支持less转为sass

**Comment by qyjandroid** [comment]
![image](https://user-images.githubusercontent.com/6645414/142159155-88ef2165-5a2b-4cec-8415-6085563dea72.png)
![image](https://user-images.githubusercontent.com/6645414/142159193-f0e764a6-fc21-4056-a1be-62179a9a67a1.png)

**Comment by TinsFox** [comment]
> 组件库创建成功了，但是新建一个组件的时候，引入了一些默认的文件找不到，虽然我可以删掉这些文件，但是我还是希望能默认补全这些文件！另外想问一下如果组件中引入图片，图片的位置有要求吗？还是是否支持less转为sass

- 一般来说组件库不会强依赖与图片等静态资源，都是使用CDN的方式使用，有需要的话应该是考虑类似 `Icon` 的组件
- 暂时只支持 `less` , sass 的支持在 2.0 cli优化完后会支持 #238 
- 引入的默认文件缺失 BaseTypeProps 晚点修复，`config-provider` 是一个[react-vant](https://3lang3.github.io/react-vant/#/zh-CN/config-provider) 的组件，引入将会在下次更新移除

**Comment by TinsFox** [comment]
上面提供的图片是使用`npm run create-component` 命令创建的组件吗？

**Comment by qyjandroid** [comment]
> 上面提供的图片是使用`npm run create-component` 命令创建的组件吗？

是的

**Comment by TinsFox** [comment]
> > 上面提供的图片是使用`npm run create-component` 命令创建的组件吗？
> 
> 是的

正在定位修复，谢谢反馈

**Comment by qyjandroid** [comment]
> > > 上面提供的图片是使用`npm run create-component` 命令创建的组件吗？
> > 
> > 
> > 是的
> 
> 正在定位修复，谢谢反馈

还需要麻烦问一下create-react-vant-cli-app 与react-vant-cli 的区别是什么呢？？ 
我目前的想法就是想创建一个空的组件库！我看create-react-vant-cli-app 是支持的

**Comment by TinsFox** [comment]
- `create-react-vant-cli-app` 是创建一个跟`react-vant` 结构一样的空组件库
- `npm run create-component` 是 给 `react-vant` 定制的快速创建新组建的命令，会依赖于 react-vant 里面的一下工具包，一开始没有想到这个命令会在空组件库里面运行。而`create-react-vant-cli-app` 创建的项目里面是没有那些工具包的，比如`BaseTypeProps`。正在考虑方案去兼容
- react-vant-cli，是react-vant的脚手架，用来编译组件库的文档、组件，以及提供一下工程化的命令如：`npm run create-component`

**Comment by qyjandroid** [comment]
> * `create-react-vant-cli-app` 是创建一个跟`react-vant` 结构一样的空组件库
> * `npm run create-component` 是 给 `react-vant` 定制的快速创建新组建的命令，会依赖于 react-vant 里面的一下工具包，一开始没有想到这个命令会在空组件库里面运行。而`create-react-vant-cli-app` 创建的项目里面是没有那些工具包的，比如`BaseTypeProps`。正在考虑方案去兼容
> * react-vant-cli，是react-vant的脚手架，用来编译组件库的文档、组件，以及提供一下工程化的命令如：`npm run create-component`

非常感谢，目前已经`react-vant` 的工具包搬移过来了，可以正常使用了，写一个一个新的组件，准备发布npm包，验证一下！

**Comment by TinsFox** [comment]
create-component 兼容空组件库 #239 

`create-component` 暂时不考虑兼容空组件库，如有需要的话可以参考指令的源码，写个简单的脚本，其实原理就是读取输入变量（组件名），然后填到预设的组件骨架字符串模板中，使用fs生成组件的文件 #101

**Comment by 3lang3** [comment]
cli已经移出仓库，采用 [rcdoc](https://github.com/3lang3/rcdoc) 构建
