### ISSUE TITLE
🐛 [react-vant-cli] create-component 兼容空组件库

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#239]
### 🐛 漏洞描述 (Bug description)

在`create-react-vant-cli-app` 创建的项目中运行`npm run create-component` ，会出现一些工具类的依赖缺失

**Comment by TinsFox** [comment]
目前 `create-component` 会强依赖 `react-vant` ，暂时不支持在其他项目中使用改指令

**Comment by 3lang3** [comment]
cli已经移出仓库，采用 [rcdoc](https://github.com/3lang3/rcdoc) 构建
