### ISSUE TITLE
🐛 [Component] xxxxx

### ISSUE THREAD

**Issue by FJHou** [3lang3/react-vant#240]
### 🐛 漏洞描述 (Bug description)

Picker 选择器搭配弹出层使用时，在惯性滚动没结束的情况下就点击确定无法选中预期的值。

### 🐾 复现步骤 (Steps to reproduce)

官网 https://3lang3.github.io/react-vant/#/zh-CN/picker，【搭配弹出层使用】demo，快速滑动，惯性滚动没结束的情况下点击确定。

### 🌈 想要的结果 (Desired result)

期望能选中滚动结束后的值

### 💻 复现示例 (Reproduce the code)

https://3lang3.github.io/react-vant/#/zh-CN/picker 【搭配弹出层使用】demo

### 📦 环境信息 (Environmental information)

- Device: [e.g. iPhone10、macOs]

### 🔖 其他 (Other)

如其他信息可以贴在这里.

If other information can be posted here.

**Comment by 3lang3** [comment]
收到 已复现

**Comment by 3lang3** [comment]
@all-contributors please add @FJHou to bug
