### ISSUE TITLE
🐛 使用组件库打包后存在问题

### ISSUE THREAD

**Issue by qyjandroid** [3lang3/react-vant#243]
### 🐛 漏洞描述 (Bug description)

使用组件库打包组件以后，实际使用的时候，一些引用找不到。
![image](https://user-images.githubusercontent.com/6645414/142173860-5dce1597-09c6-4228-a631-f46993b2085f.png)

修改为es或者lib后，又出现其他问题
![image](https://user-images.githubusercontent.com/6645414/142173952-7ced19c9-c6aa-4da1-a18a-89231addfaeb.png)

![image](https://user-images.githubusercontent.com/6645414/142174002-a379e33a-e512-474f-a9ff-4b479c702550.png)

### 🐾 复现步骤 (Steps to reproduce)

使用create-react-vant-cli-app 创建了组件库，并且使用创建组件命令生成了一个Loading 组件。
1. 运行build 命令 生成es,lib 
2.  修改package.json  的字段name:live-react-com
3. 其他项目中使用Loading组件
### 🌈 想要的结果 (Desired result)

想要直接 使用  import { Loading } from 'live-react-com';  自动导入。组件中的引用也正常打包。

**Comment by 3lang3** [comment]
@qyjandroid 看报错信息：
> Can't resolve 'clsx' ... 

看下loading组件内什么情况

@0x219 是不是clsx替换这部分影响了。。

**Comment by qyjandroid** [comment]
> @qyjandroid 看报错信息：
> 
> > Can't resolve 'clsx' ...
> 
> 看下loading组件内什么情况
> 
> @0x219 是不是clsx替换这部分影响了。。

![image](https://user-images.githubusercontent.com/6645414/142176629-917ae95c-c8d5-42b9-870c-c5118d2d31ea.png)
![image](https://user-images.githubusercontent.com/6645414/142176743-428ea8b9-c047-4d95-8f00-a962034136ac.png)
![image](https://user-images.githubusercontent.com/6645414/142176827-ee8ba77e-0335-4a40-a0bf-a3ee766ab63f.png)

组件正常运行，demo也演示通过

**Comment by TinsFox** [comment]
问题是`packages/create-react-vant-cli-app/generators/react/package.json.tpl` 的 `devDependencies` 中没有 `clsx` 引起的，手动安装一下就好了，`yarn add clax -D`

**Comment by qyjandroid** [comment]
> 问题是`packages/create-react-vant-cli-app/generators/react/package.json.tpl` 的 `devDependencies` 中没有 `clsx` 引起的，手动安装一下就好了，`yarn add clax -D`

组件库引用的时候怎么引用呢？？
可以直接这样吗？ 
import { Loading } from 'live-react-com';
我们我这样是报错的，我是那里配置错了吗？？

**Comment by 0x219** [comment]
我待会晚点看一下

**Comment by qyjandroid** [comment]
> 我待会晚点看一下

好的，太感谢了，给个赞！！

**Comment by TinsFox** [comment]
> > 问题是`packages/create-react-vant-cli-app/generators/react/package.json.tpl` 的 `devDependencies` 中没有 `clsx` 引起的，手动安装一下就好了，`yarn add clax -D`
> 
> 组件库引用的时候怎么引用呢？？ 可以直接这样吗？ import { Loading } from 'live-react-com'; 我们我这样是报错的，我是那里配置错了吗？？

这是在项目A中引用了你创建的组件库吗？这样的用法要 `npm link`。可以的话推到github，给个复现demo吧

**Comment by 3lang3** [comment]
@qyjandroid 看下react-com-libs的package.json

**Comment by qyjandroid** [comment]
> @qyjandroid 看下react-com-libs的package.json

```json
{
    "name": "live-react-com",
    "version": "1.0.0",
    "description": "",
    "main": "lib/react-com-libs.js",
    "style": "lib/index.css",
    "files": [
        "lib",
        "es"
    ],
    "scripts": {
        "start": "react-vant-cli dev",
        "create-component": "react-vant-cli create-component",
        "postcreate-component": "yarn prettier",
        "prettier": "npx prettier --write vant.config.js src/index.ts",
        "build": "react-vant-cli build",
        "release": "react-vant-cli release --tag dev",
        "build:site": "react-vant-cli build-site",
        "release:site": "npm run build:site && gh-pages -d site",
        "prepack": "yarn build"
    },
    "author": "",
    "license": "MIT",
    "peerDependencies": {
        "react": ">=16.14.0",
        "react-dom": ">=16.14.0"
    },
    "devDependencies": {
        "@react-vant/cli": "^1.1.12",
        "@types/react": "^16.9.55",
        "@types/react-dom": "^16.9.9",
        "react": "^17.0.2",
        "react-dom": "^17.0.2"
    },
    "lint-staged": {
        "*.md": "prettier --write",
        "*.{ts,tsx,js,vue,less,scss}": "prettier --write",
        "*.{ts,tsx,js,vue}": "eslint --fix",
        "*.{vue,css,less,scss}": "stylelint --fix"
    },
    "browserslist": [
        "Android >= 4.0",
        "iOS >= 8"
    ]
}
```

**Comment by 0x219** [comment]
> > @qyjandroid 看下react-com-libs的package.json
> 
> ```json
> {
>     "name": "live-react-com",
>     "version": "1.0.0",
>     "description": "",
>     "main": "lib/react-com-libs.js",
>     "style": "lib/index.css",
>     "files": [
>         "lib",
>         "es"
>     ],
>     "scripts": {
>         "start": "react-vant-cli dev",
>         "create-component": "react-vant-cli create-component",
>         "postcreate-component": "yarn prettier",
>         "prettier": "npx prettier --write vant.config.js src/index.ts",
>         "build": "react-vant-cli build",
>         "release": "react-vant-cli release --tag dev",
>         "build:site": "react-vant-cli build-site",
>         "release:site": "npm run build:site && gh-pages -d site",
>         "prepack": "yarn build"
>     },
>     "author": "",
>     "license": "MIT",
>     "peerDependencies": {
>         "react": ">=16.14.0",
>         "react-dom": ">=16.14.0"
>     },
>     "devDependencies": {
>         "@react-vant/cli": "^1.1.12",
>         "@types/react": "^16.9.55",
>         "@types/react-dom": "^16.9.9",
>         "react": "^17.0.2",
>         "react-dom": "^17.0.2"
>     },
>     "lint-staged": {
>         "*.md": "prettier --write",
>         "*.{ts,tsx,js,vue,less,scss}": "prettier --write",
>         "*.{ts,tsx,js,vue}": "eslint --fix",
>         "*.{vue,css,less,scss}": "stylelint --fix"
>     },
>     "browserslist": [
>         "Android >= 4.0",
>         "iOS >= 8"
>     ]
> }
> ```
dependencies缺少clsx 模板成本的问题 晚点改一下。你这边可以先自行添加clax依赖就行了

**Comment by qyjandroid** [comment]
> > > 问题是`packages/create-react-vant-cli-app/generators/react/package.json.tpl` 的 `devDependencies` 中没有 `clsx` 引起的，手动安装一下就好了，`yarn add clax -D`
> > 
> > 
> > 组件库引用的时候怎么引用呢？？ 可以直接这样吗？ import { Loading } from 'live-react-com'; 我们我这样是报错的，我是那里配置错了吗？？
> 
> 这是在项目A中引用了你创建的组件库吗？这样的用法要 `npm link`。可以的话推到github，给个复现demo吧

已推送到github
组件库地址：https://github.com/qyjandroid/react-com-libs
项目中引用：https://github.com/qyjandroid/test-react-com-libs，组件引用目录:src/pages/Home/index.tsx
组件库直接发包了，可以直接在npm包中搜索live-react-com

还有一个问题，项目中配置了babel-import-plugin,自动按需引入，但是引入的没有样式？？
![image](https://user-images.githubusercontent.com/6645414/142187646-cad0ed64-8ba8-468f-8591-e07b6f38dfb8.png)

**Comment by qyjandroid** [comment]
> > > @qyjandroid 看下react-com-libs的package.json
> > 
> > 
> > ```json
> > {
> >     "name": "live-react-com",
> >     "version": "1.0.0",
> >     "description": "",
> >     "main": "lib/react-com-libs.js",
> >     "style": "lib/index.css",
> >     "files": [
> >         "lib",
> >         "es"
> >     ],
> >     "scripts": {
> >         "start": "react-vant-cli dev",
> >         "create-component": "react-vant-cli create-component",
> >         "postcreate-component": "yarn prettier",
> >         "prettier": "npx prettier --write vant.config.js src/index.ts",
> >         "build": "react-vant-cli build",
> >         "release": "react-vant-cli release --tag dev",
> >         "build:site": "react-vant-cli build-site",
> >         "release:site": "npm run build:site && gh-pages -d site",
> >         "prepack": "yarn build"
> >     },
> >     "author": "",
> >     "license": "MIT",
> >     "peerDependencies": {
> >         "react": ">=16.14.0",
> >         "react-dom": ">=16.14.0"
> >     },
> >     "devDependencies": {
> >         "@react-vant/cli": "^1.1.12",
> >         "@types/react": "^16.9.55",
> >         "@types/react-dom": "^16.9.9",
> >         "react": "^17.0.2",
> >         "react-dom": "^17.0.2"
> >     },
> >     "lint-staged": {
> >         "*.md": "prettier --write",
> >         "*.{ts,tsx,js,vue,less,scss}": "prettier --write",
> >         "*.{ts,tsx,js,vue}": "eslint --fix",
> >         "*.{vue,css,less,scss}": "stylelint --fix"
> >     },
> >     "browserslist": [
> >         "Android >= 4.0",
> >         "iOS >= 8"
> >     ]
> > }
> > ```
> 
> dependencies缺少clsx 模板生成的问题 晚点改一下。你这边可以先自行添加clsx依赖就行了

已在具体项目中添加了clxs 包

**Comment by 0x219** [comment]
okvia Newton MailOn Wed, Nov 17, 2021 at 6:56pm, quanyj ***@***.***> ***@***.*** 看下react-com-libs的package.json{

    "name": "live-react-com",

    "version": "1.0.0",

    "description": "",

    "main": "lib/react-com-libs.js",

    "style": "lib/index.css",

    "files": [

        "lib",

        "es"

    ],

    "scripts": {

        "start": "react-vant-cli dev",

        "create-component": "react-vant-cli create-component",

        "postcreate-component": "yarn prettier",

        "prettier": "npx prettier --write vant.config.js src/index.ts",

        "build": "react-vant-cli build",

        "release": "react-vant-cli release --tag dev",

        "build:site": "react-vant-cli build-site",

        "release:site": "npm run build:site && gh-pages -d site",

        "prepack": "yarn build"

    },

    "author": "",

    "license": "MIT",

    "peerDependencies": {

        "react": ">=16.14.0",

        "react-dom": ">=16.14.0"

    },

    "devDependencies": {

        ***@***.***/cli": "^1.1.12",

        ***@***.***/react": "^16.9.55",

        ***@***.***/react-dom": "^16.9.9",

        "react": "^17.0.2",

        "react-dom": "^17.0.2"

    },

    "lint-staged": {

        "*.md": "prettier --write",

        "*.{ts,tsx,js,vue,less,scss}": "prettier --write",

        "*.{ts,tsx,js,vue}": "eslint --fix",

        "*.{vue,css,less,scss}": "stylelint --fix"

    },

    "browserslist": [

        "Android >= 4.0",

        "iOS >= 8"

    ]

}dependencies缺少clsx 模板生成的问题 晚点改一下。你这边可以先自行添加clsx依赖就行了已在具体项目中添加了clxs 包—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.[

{

***@***.***": "schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "github.com/3lang3/react-vant/issues/243#issuecomment-971462392",

"url": "github.com/3lang3/react-vant/issues/243#issuecomment-971462392",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "github.com"

}

}

]

**Comment by qyjandroid** [comment]
> okvia Newton MailOn Wed, Nov 17, 2021 at 6:56pm, quanyj ***@***.***> ***@***.*** 看下react-com-libs的package.json{ "name": "live-react-com", "version": "1.0.0", "description": "", "main": "lib/react-com-libs.js", "style": "lib/index.css", "files": [ "lib", "es" ], "scripts": { "start": "react-vant-cli dev", "create-component": "react-vant-cli create-component", "postcreate-component": "yarn prettier", "prettier": "npx prettier --write vant.config.js src/index.ts", "build": "react-vant-cli build", "release": "react-vant-cli release --tag dev", "build:site": "react-vant-cli build-site", "release:site": "npm run build:site && gh-pages -d site", "prepack": "yarn build" }, "author": "", "license": "MIT", "peerDependencies": { "react": ">=16.14.0", "react-dom": ">=16.14.0" }, "devDependencies": { ***@***.***/cli": "^1.1.12", ***@***.***/react": "^16.9.55", ***@***.***/react-dom": "^16.9.9", "react": "^17.0.2", "react-dom": "^17.0.2" }, "lint-staged": { "*.md": "prettier --write", "*.{ts,tsx,js,vue,less,scss}": "prettier --write", "*.{ts,tsx,js,vue}": "eslint --fix", "*.{vue,css,less,scss}": "stylelint --fix" }, "browserslist": [ "Android >= 4.0", "iOS >= 8" ] }dependencies缺少clsx 模板生成的问题 晚点改一下。你这边可以先自行添加clsx依赖就行了已在具体项目中添加了clxs 包—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.[ { ***@***.***": "schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "github.com/3lang3/react-vant/issues/243#issuecomment-971462392", "url": "github.com/3lang3/react-vant/issues/243#issuecomment-971462392", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "github.com" } } ]

？？？？？没看明白

**Comment by qyjandroid** [comment]
我查看了下babel-plugin-import 文档，修改了babel配置：
![image](https://user-images.githubusercontent.com/6645414/142342656-ee668e17-559e-4626-be46-5fc78cf0d1ae.png)
这里style必须配置index.css,插件才会找live-react-com/lib/loading/style/index.css 。

配置好bable以后：
![image](https://user-images.githubusercontent.com/6645414/142342854-22c5def5-e50c-42ed-afa9-e012ac6d97c2.png)

这样修改以后，虽然说有提示信息，但是可以编译成功！

我查看编译后有没有打包css,结果还是和以前一样，没有看到样式生效！

**Comment by qyjandroid** [comment]
找到原因了！
![image](https://user-images.githubusercontent.com/6645414/142346429-4829b268-870c-4ab6-a99a-b88fd53fb4c2.png)
我手动修改了打包好的组件库中的index.js ，修改require("../../style/base.less) 为css，就可以了！！

因为我的项目是scss 打包的，没有装less 的插件，也不想再装一个！这块是否可以优化一下，打包组件库的时候style/index.js 可以直接引用css文件吗？？？

**Comment by 3lang3** [comment]
@qyjandroid 非常抱歉，当前cli打包产物样式文件默认导出的是less，项目中使用的话需要配置less相关才行，等我们cli升级吧

**Comment by qyjandroid** [comment]
好的



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月18日 12:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [3lang3/react-vant] 🐛 使用组件库打包后存在问题 (Issue #243) |

@qyjandroid 非常抱歉，当前cli打包产物样式文件默认导出的是less，项目中使用的话需要配置less相关才行，等我们cli升级吧

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 3lang3** [comment]
或者`babel-import-plugin`配置成这样试试
```
...
style: (name) => `react-vant/es/${name}/style/index.css`
```

**Comment by 3lang3** [comment]
最近已经在着手了，具体工作在next分支展开

**Comment by qyjandroid** [comment]
> 最近已经在着手了，具体工作在next分支展开

您好，next 分支大概什么时候发布呢？

**Comment by 3lang3** [comment]
肯定要年后啦，可以看下project具体任务

**Comment by qyjandroid** [comment]
> 肯定要年后啦，可以看下project具体任务

您好，看了下project具体任务，这个需求没有在进行中呢？想利用这个cli 开发一套内部用的组件库，需求还是挺迫切的。

**Comment by 3lang3** [comment]
> > 肯定要年后啦，可以看下project具体任务
> 
> 您好，看了下project具体任务，这个需求没有在进行中呢？想利用这个cli 开发一套内部用的组件库，需求还是挺迫切的。

抱歉哈 cli已经计划单独出来了，正在开发中，如果很急的话 建议使用dumi哦

**Comment by 3lang3** [comment]
cli已经移出仓库，采用 [rcdoc](https://github.com/3lang3/rcdoc) 构建
