### ISSUE TITLE
🐛 [Cell] `rightIconSlot` 属性 丢失

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#245]
### 🐛 漏洞描述 (Bug description)

TS 类型错误 Cell 没有`rightIconSlot` 属性

![image](https://user-images.githubusercontent.com/33956589/142349391-c67e1b5c-f33e-40ba-9a12-f611cd9b4400.png)

**Comment by 3lang3** [comment]
没有`rightIconSlot`，是`rightIcon`
