### ISSUE TITLE
 [Calendar] no properties for month title and week days

### ISSUE THREAD

**Issue by AdonLee** [3lang3/react-vant#263]
**Is your feature request related to a problem? Please describe.**
for supporting i18n, we need to change the default text

**Describe the solution you'd like**
Maybe enrich the formatter property is a good choice, you can change all in on place

**Comment by 3lang3** [comment]
i18n will be support in 2.x version, we're working on this (branch: `next` )
for now, i plan to add some props compatible implement it.

**Comment by 3lang3** [comment]
@all-contributors please add @chinieer to ideas

**Comment by 3lang3** [comment]
@all-contributors please add @AdonLee to ideas

**Comment by 3lang3** [comment]
@AdonLee 
Is there anything else you need to change the default text? I can adjust together

**Comment by AdonLee** [comment]
> @AdonLee Is there anything else you need to change the default text? I can adjust together
暂时没有其他，新版本大概什么上?这边急着用....
