### ISSUE TITLE
🐛 [Component] Cell `arrowDirection` 为 `right` 时向右箭头消失了

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#268]
### 🐛 漏洞描述 (Bug description)

![image](https://user-images.githubusercontent.com/33956589/144369468-033a39aa-c918-42ba-9e69-90752ab8181b.png)
![image](https://user-images.githubusercontent.com/33956589/144369792-518d4f39-b1bd-4362-9064-50b8fe9cab8c.png)

Cell `arrowDirection` 为 `right` 时向右箭头消失了

### 🌈 想要的结果 (Desired result)

根据场景设置箭头的方向，实现手风琴效果

Describe what you expected to see.

### 💻 复现示例 (Reproduce the code)

```jsx
<Cell title="单元格" isLink arrowDirection="right" value="内容" />
```

**Comment by 3lang3** [comment]
这是个bug，虽然默认是right，但是后续逻辑忽略了right值导致返回了null
