### ISSUE TITLE
🐛 [Bug]: stepper值为0 页面显示为空

### ISSUE THREAD

**Issue by GangYHu** [3lang3/react-vant#283]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `@react-vant/cli`
- [ ] `create-react-vant-cli-app`

### What version of React Vant are you using?

"react-vant": "^1.4.3"

### What version of Node are you using? Minimum supported version is 12.

16.13

### Steps to Reproduce

设置初始状态或者通过减号把值改为0的 页面显示无内容

### Expected Behavior

能正常显示0

### Actual Behavior

无

**Comment by 3lang3** [comment]
收到

**Comment by 3lang3** [comment]
@all-contributors please add @GangYHu to bug
