### ISSUE TITLE
🐛 [Bug]: lockscroll does not work on safari-ios

### ISSUE THREAD

**Issue by AdonLee** [3lang3/react-vant#284]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `@react-vant/cli`
- [ ] `create-react-vant-cli-app`

### What version of React Vant are you using?

1.4.7

### What version of Node are you using? Minimum supported version is 12.

14.16.2

### Steps to Reproduce

```html
<div style={{height: '200vh'}}>
     <Popup visible={true}>
           <p>popup content</p>
     <Popup>
</div>
```

### Expected Behavior

prevent screen scroll when touch move on Overlay

### Actual Behavior

page still scroll when touch move

### Context

it may affects by the passive option which is set true by default. you can pass the `touch-action: none` to overlayStyle to fix it but safari does not support it until version 13

**Comment by 3lang3** [comment]
@AdonLee  Do u have time to create pr for this issue?

**Comment by AdonLee** [comment]
@3lang3 Of course, i have create a pr for this issue

**Comment by 3lang3** [comment]
@AdonLee thx!
