### ISSUE TITLE
🐛 [Bug]: The offset of the active anchor is doubled when activating by IndexBar in Popup on IOS 

### ISSUE THREAD

**Issue by AdonLee** [3lang3/react-vant#288]
### Which React Vant packages are impacted?

- [x] `react-vant` (React Vant core)
- [ ] `@react-vant/cli`
- [ ] `create-react-vant-cli-app`

### What version of React Vant are you using?

1.14.7

### What version of Node are you using? Minimum supported version is 12.

14.16.2

### Steps to Reproduce

set a value to the stickyOffset, then click the index bar to activate a new anchor

### Expected Behavior

sticky on correct positioin

### Actual Behavior

the actual offset is doubled

### Context

Any browser in IOS

**Comment by 3lang3** [comment]
I didn't reproduce this bug, Is it convenient to create codesandbox demo？

**Comment by AdonLee** [comment]
@3lang3  Here is the demo: https://codesandbox.io/s/jovial-panini-800ur?file=/src/App.js
Note that it works find in the inner window, you need open it in new window at the top-right corner

**Comment by 3lang3** [comment]
@AdonLee  thx for demo.
This problem only occurs when `IndexBar` wrapped by `Popup`. Is it necessary to reconsider #289  ?

**Comment by AdonLee** [comment]
@3lang3 It desn't make sense to set the scrollTop property of body, but cause this issue.

**Comment by AdonLee** [comment]
@3lang3 Embarrassed to find that #289 is necesssary to reconsider. I annotated the wrong code, It works for me as i comment out `setScrollTop(window, value);`, But it is not the core of the problem. The point is that when the indexbar is placed is in the popup, the popup(the scroll parent), not the window, should scroll for the stickyOffsetTop. int this case, the window will scroll minus scrollOffsetTop results in a wrong scrollParentRect.

**Comment by 3lang3** [comment]
@AdonLee `setScrollTop` and `setRootScrollTop` is a difference in the definition. needs to be sure that no other problems will arise

**Comment by 3lang3** [comment]
I had reviewd #293. pls confirm

**Comment by AdonLee** [comment]
> I had reviewd #293. pls confirm

Thanks, i'm confirmed.

**Comment by 3lang3** [comment]
@AdonLee sorry for late reply, one more question is that #289 need revert?

**Comment by AdonLee** [comment]
@3lang3 it's a good choice to revert for unconsidered case

**Comment by 3lang3** [comment]
@AdonLee merged #293 and I adjust it slightly to determine whether it is under `Popup`, Pls test your cases, when you confirm there is no problem, I will release.

**Comment by AdonLee** [comment]
@3lang3  It works fine now.

**Comment by 3lang3** [comment]
released in v1.4.10
