### ISSUE TITLE
🐛 [Bug]: validateTrigger: onBlur 不生效

### ISSUE THREAD

**Issue by U1in** [3lang3/react-vant#294]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `@react-vant/cli`
- [ ] `create-react-vant-cli-app`

### What version of React Vant are you using?

react-vant@1.4.9

### What version of Node are you using? Minimum supported version is 12.

v12.16.0

### Steps to Reproduce

`<Form.Item rule={[{ pattern: /\S{2,32}/, message: "....", validateTrigger: "onBlur" }}>{....}</Form.Item>`

### Expected Behavior

当失焦时候触发检查

### Actual Behavior

输入时候没有检查，失焦也没有检查

**Comment by U1in** [comment]
第一次使用，不知道是不是使用方式不对

**Comment by 3lang3** [comment]
@U1in 确实有问题 ，稍后修复

**Comment by 3lang3** [comment]
> 第一次使用，不知道是不是使用方式不对

抱歉，刚去看了[rc-field-form](https://github.com/react-component/field-form)文档，代码没问题的
eg:
```js
 <Form.Item
  // rule的validateTrigger属性必须是父级Form.Item validateTrigger的子集
  validateTrigger={['onBlur', 'onFocus']}
  rules={[
    //  这条rule只会在onBlur时触发
   { required: true, message: '请填写密码', validateTrigger: 'onBlur' },
   // 这条rule只会在onFocus时触发
   { required: true, message: '请填写密码', validateTrigger: 'onFocus' },
   // 这条rule onBlur和onFocus都会触发
   { required: true, message: '请填写密码' }
  ]}
  name="password"
  label="密码"
>
  <Field placeholder="请输入密码" />
</Form.Item>
```

**Comment by U1in** [comment]
> 



> > 第一次使用，不知道是不是使用方式不对
> 
> 抱歉，刚去看了[rc-field-form](https://github.com/react-component/field-form)文档，代码没问题的 eg:
> 
> ```js
>  <Form.Item
>   // rule的validateTrigger属性必须是父级Form.Item validateTrigger的子集
>   validateTrigger={['onBlur', 'onFocus']}
>   rules={[
>     //  这条rule只会在onBlur时触发
>    { required: true, message: '请填写密码', validateTrigger: 'onBlur' },
>    // 这条rule只会在onFocus时触发
>    { required: true, message: '请填写密码', validateTrigger: 'onFocus' },
>    // 这条rule onBlur和onFocus都会触发
>    { required: true, message: '请填写密码' }
>   ]}
>   name="password"
>   label="密码"
> >
>   <Field placeholder="请输入密码" />
> </Form.Item>
> ```

辛苦回复，我待会尝试一下

**Comment by 3lang3** [comment]
@U1in 客气

**Comment by U1in** [comment]
> ```js
> validateTrigger: 'onBlur'
> ```

这个方法可行

**Comment by U1in** [comment]
> > 第一次使用，不知道是不是使用方式不对
> 
> 抱歉，刚去看了[rc-field-form](https://github.com/react-component/field-form)文档，代码没问题的 eg:
> 
> ```js
>  <Form.Item
>   // rule的validateTrigger属性必须是父级Form.Item validateTrigger的子集
>   validateTrigger={['onBlur', 'onFocus']}
>   rules={[
>     //  这条rule只会在onBlur时触发
>    { required: true, message: '请填写密码', validateTrigger: 'onBlur' },
>    // 这条rule只会在onFocus时触发
>    { required: true, message: '请填写密码', validateTrigger: 'onFocus' },
>    // 这条rule onBlur和onFocus都会触发
>    { required: true, message: '请填写密码' }
>   ]}
>   name="password"
>   label="密码"
> >
>   <Field placeholder="请输入密码" />
> </Form.Item>
> ```

这个方法可行，可以关闭问题了
