### ISSUE TITLE
可以直接申请到有赞团队下吧，这个弄的挺好的

### ISSUE THREAD

**Issue by glzcc** [3lang3/react-vant#3]

**Comment by 3lang3** [comment]
现在在公司内部试点，实践起来还是有挺多问题。

精力有限等正式版出来再说🤔

**Comment by ratelgogo** [comment]
支持，希望有机会贡献代码，不过我是个后端，前端技术没信心😏

**Comment by 3lang3** [comment]
@ratelgogo ui库对于你们后端应该还是没问题的，逻辑简单，项目现在小问题挺多，等你的pr😄

**Comment by 3lang3** [comment]
已经被vant拉入到readme里面了。

**Comment by mxdi9i7** [comment]
羡慕 有公司赞助，我这边基本太监了

**Comment by 3lang3** [comment]
> 羡慕 有公司赞助，我这边基本太监了

都是社区在弄，没有公司赞助啦

**Comment by codedart2018** [comment]
vant 官方的还是社区爱好的？

**Comment by 3lang3** [comment]
> vant 官方的还是社区爱好的？

非官方 社区的
