### ISSUE TITLE
🐛 [Bug]: Typography.Text with ellipsis dosn't work in Button

### ISSUE THREAD

**Issue by AdonLee** [3lang3/react-vant#305]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `@react-vant/cli`
- [ ] `create-react-vant-cli-app`

### What version of React Vant are you using?

1.4.10

### What version of Node are you using? Minimum supported version is 12.

14.16.1

### Steps to Reproduce

```html
<Button style={{width: '100px'}}>
    <Typography.Text ellipsis >a long long text a long long text a long long text a long long text<Typography.Text>
</Button>
```

### Expected Behavior

work as expected

### Actual Behavior

not work

**Comment by 3lang3** [comment]
@AdonLee fix on main but not release
