### ISSUE TITLE
🐛 [Bug]: Stepper手动输入value变化

### ISSUE THREAD

**Issue by JR0613** [3lang3/react-vant#314]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `@react-vant/cli`
- [ ] `create-react-vant-cli-app`

### What version of React Vant are you using?

React Vant

### What version of Node are you using? Minimum supported version is 12.

1.4.11

### Steps to Reproduce

bug复现:
1: 当设置min时,无法通过输入框手动改变value大小;
例如: min=3,手动删除value为空时,再输入一个9,onChange方法执行了两次,第一次输出值为9,第二次输出值为3,最终value是3,无法实现手动输入值的变化
2: 当输入值为两位数时,value的第一个值显示的是min,删除个位数,value显示各位数
例如: min=0,手动输入32,实际输出为02,删除2之后,应为0,实际输出为2

### Expected Behavior

设置min时,手动输入小于min则返回min,大于min小于max,则取输入的value

### Actual Behavior

删除value为null时,输入个位数,输出结果为min;输入两位数时,十位为min,删除个位数是,输出结果为原来的个位数

**Comment by JR0613** [comment]
这个问题是给关了是么?

**Comment by 3lang3** [comment]
@JR0613 已经修复了
