### ISSUE TITLE
✨ [Feature]: 文档标题锚点

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#317]
### What is the new or updated feature that you are suggesting?

在文档的左侧加个标题的锚点跳转，方便在长篇文档之间的跳转
![image](https://user-images.githubusercontent.com/33956589/153140841-7e35b83c-23dc-4e3c-b4da-ac25f2ddcaa4.png)

### Why should this feature be included?

提高用户体验

**Comment by 3lang3** [comment]
这个可以有

**Comment by 3lang3** [comment]
锚点已经在开发了吗，由于使用的是HashRouter 会造成hash跳转失败问题，需要时间修复

**Comment by TinsFox** [comment]
> 锚点已经在开发了吗，由于使用的是HashRouter 会造成hash跳转失败问题，需要时间修复

没有啊，还没看插件怎么写的，加个 `Doing` 的label吧，管理issue的处理状态

**Comment by 3lang3** [comment]
部署在github上配置不了nginx， rv的文档无法使用BrowerHistoy，现有锚点先使用降级方案。

**Comment by TinsFox** [comment]
目录放在右侧好像会比较好？现在在左侧滚动文档会吸引注意力

**Comment by 3lang3** [comment]
右侧和demo展示区域互相干扰 还会割裂页面，现在位置和左侧导航结构类似，视觉过渡比较自然
