### ISSUE TITLE
✨ [Feature]: 文档prop复制

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#318]
### What is the new or updated feature that you are suggesting?

![image](https://user-images.githubusercontent.com/33956589/153143416-1fab0ae9-d8cc-4c45-9d59-fe63f9ca4d5c.png)
![image](https://user-images.githubusercontent.com/33956589/153143442-e830c85c-bfae-4b36-a680-b2d754bed1f0.png)

加个复制功能，感觉有会体验好点，没有也无所谓

### Why should this feature be included?

增强用户体验

**Comment by 3lang3** [comment]
页面元素太多，复制ui不还好弄，单纯加复制功能简单。

**Comment by TinsFox** [comment]
在这些要复制的属性加个点击复制就好了

**Comment by 3lang3** [comment]
后面脚手架弄好后 在以主题的形式去支持这些功能吧 和dumi theme一样

**Comment by TinsFox** [comment]
> 后面脚手架弄好后 在以主题的形式去支持这些功能吧 和dumi theme一样

可以 出个换肤功能👍
