### ISSUE TITLE
🐛 [Bug]: node 12.x 支持

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#319]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [X] `@react-vant/cli`
- [ ] `create-react-vant-cli-app`

### What version of React Vant are you using?

2.0.0-alpha.19

### What version of Node are you using? Minimum supported version is 12.

12.22.7

### Steps to Reproduce

```
gcl
pnpm i
pnpm dev
```

### Expected Behavior

启动不报错

### Actual Behavior

```
/react-vant/packages/react-vant-cli/lib/common/constant.js:73
const vantConfig = await getVantConfigAsync();
                   ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)

```

### Context

切换至node 14.x 正常启动 ，对node支持是否最低版本已经要求14.x了

**Comment by 3lang3** [comment]
是的，转成vite后使用了top await，node最低版本需要14.x了
