### ISSUE TITLE
🐛 [Bug]: vite less loader

### ISSUE THREAD

**Issue by songhn233** [3lang3/react-vant#330]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `@react-vant/cli`
- [ ] `create-react-vant-cli-app`

### What version of React Vant are you using?

2.0.0-alpha.20

### What version of Node are you using? Minimum supported version is 12.

16.0.0

### Steps to Reproduce

运行官方 vite demo
![image](https://user-images.githubusercontent.com/47357585/157936307-e55567dc-e6db-4668-a6e2-a3ad00618652.png)
重复引入大量全量 css 文件（在只 tree-shaking 引入 btn 的情况下）

打包后依然存在相同问题
![image](https://user-images.githubusercontent.com/47357585/157936497-6c81361b-506b-416e-9da5-4321fd5460b9.png)

看起来和这两个问题类似，应该是 less 被重复引入了

- https://github.com/vbenjs/vite-plugin-style-import/issues/17
- https://github.com/ElemeFE/element/issues/11817

### Expected Behavior

在 dev & build 下正常 tree shaking

### Actual Behavior

重复全量引入多次

**Comment by 3lang3** [comment]
应该只有vite build有这个问题吧那？

**Comment by songhn233** [comment]
> 应该只有vite build有这个问题吧那？
vite dev 和 build 都有类似情况

**Comment by 3lang3** [comment]
我试了下，vite dev下确实重复引入了，vite build是全量打包了css，tree shaking没起作用，没出现重复的情况。

**Comment by zcyc** [comment]
您好，这个修复了吗？

**Comment by 3lang3** [comment]
正在弄，近期会更新一版 升级整个vite的构建流程

**Comment by 3lang3** [comment]
最新版本已经修复
[官方demo](https://github.com/3lang3/react-vant-template/tree/main/next/vite) 已验证
