### ISSUE TITLE
🐛 [Bug]: 不能将类型“"small"”分配给类型“"large"”。ts(2322)

### ISSUE THREAD

**Issue by JohnieXu** [3lang3/react-vant#335]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `@react-vant/cli`
- [ ] `create-react-vant-cli-app`

### What version of React Vant are you using?

react-vant@2.0.0-alpha.27

### What version of Node are you using? Minimum supported version is 12.

v14.17.6

### Steps to Reproduce

`<Cell>`组件报类型错误
```jsx
<Cell.Group card className="input-box">
          <Cell title="秘钥" label="请选择秘钥" isLink size="small" onClick={() => setShowAppkeyPicker(true)}>
            <Field
              value={appkey}
              readonly
            ></Field>
          </Cell>
</Cell.Group>
```
```ts
(property) CellProps.size?: "large" | undefined
单元格大小

不能将类型“"small"”分配给类型“"large"”。ts(2322)
[PropsType.d.ts(12, 5): ]()所需类型来自属性 "size"，在此处的 "IntrinsicAttributes & CellProps & { children?: ReactNode; }" 类型上声明该属性
```

### Expected Behavior

不报类型错误

### Actual Behavior

报类型错误：不能将类型“"small"”分配给类型“"large"”。ts(2322)

**Comment by 3lang3** [comment]
OK pr welcome

**Comment by ovensi** [comment]
> OK pr welcome

这个size属性本身就只有large可选，去看了Vant的文档也是只有large，这个不算是bug。

**Comment by 3lang3** [comment]
> > OK pr welcome
> 
> 这个size属性本身就只有large可选，去看了Vant的文档也是只有large，这个不算是bug。

我去看了下 确实是这样，那先关闭了

**Comment by JohnieXu** [comment]
感谢哈！
