### ISSUE TITLE
✨ [Feature]: 支持formilyjs

### ISSUE THREAD

**Issue by phpmaple** [3lang3/react-vant#343]
### What is the new or updated feature that you are suggesting?

我看 vant 的 vue 版本支持了 有计划支持一下吗? https://formilyjs.org/zh-CN/guide

### Why should this feature be included?

简化表单

**Comment by 3lang3** [comment]
近期没时间弄这个，后面我评估下吧

**Comment by 3lang3** [comment]
你说的支持formilyjs是指？ react-vant是ui层面的组建 按理来说不影响使用formilyjs啊
