### ISSUE TITLE
[SSR] Toast: document is not defined

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#36]
**Describe the bug**
next 中使用Toast动态更新方法提示
`document is not defined`

**To Reproduce**
```bash
git clone https://github.com/TinsFox/next-reavt-vant.git
cd next-reavt-vant
yarn && yarn run dev
```
访问`http://localhost:7000/toast`

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/33956589/132471645-02d1f2be-b3e5-4820-8560-7eb5ce530ec5.png)

**Comment by 3lang3** [comment]
ssr场景下，动态更新失效
