### ISSUE TITLE
🐛 [Bug]: uploader组件点击预览的 popup 的遮罩不能关闭预览吗

### ISSUE THREAD

**Issue by phpmaple** [3lang3/react-vant#362]
### Which React Vant packages are impacted?

- [x] `react-vant` (React Vant core)
- [ ] `@react-vant/cli`
- [ ] `create-react-vant-cli-app`

### What version of React Vant are you using?

2.0.0-alpha.26

### What version of Node are you using? Minimum supported version is 12.

v16.14.2

### Steps to Reproduce

RT

### Expected Behavior

可以选择性点击 overlay 关闭

### Actual Behavior

不能选择, 默认点击不关闭

**Comment by 3lang3** [comment]
嗯 现在是点击图片关闭，下个版本修复下
也欢迎👏 pr啊 最近挺忙的

**Comment by 3lang3** [comment]
release on [2.0.0-alpha.34](https://www.npmjs.com/package/react-vant/v/2.0.0-alpha.34) 🚀
