### ISSUE TITLE
How to get the dom instance of the <Collapse/> component?

### ISSUE THREAD

**Issue by wild-sky** [3lang3/react-vant#365]
How can I get the DOM instance of the <Collapse /> component? I read the document, but the official ref can only call toggle. Is the next step planned to add methods that can obtain component instances?

**Comment by 3lang3** [comment]
you mean all components dom instance?

**Comment by 3lang3** [comment]
release on [2.0.0-alpha.34](https://www.npmjs.com/package/react-vant/v/2.0.0-alpha.34) 🚀

**Comment by wild-sky** [comment]
aha, very thanks!

**Comment by 3lang3** [comment]
https://react-vant.3lang.dev/components/collapse

the doc updated! 
Now, you can use nativeRef prop to get component dom instance
