### ISSUE TITLE
✨ [Feature]: Picker columnsFieldNames

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#377]
### What is the new or updated feature that you are suggesting?

Column 数据结构增加个泛型？

### Why should this feature be included?

Column 数据结构
values的类型现在是Array<string | number>，我在使用过程中会传这样的数据 { label, value }[]

```js
options: [{label: "选项一", value: 1}, {label: "选项二", value: 2}]
0: {label: "选项一", value: 1}
1: {label: "选项二", value: 2}
```
在回调的时候类型的获取有点问题
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/33956589/166876838-3ea97934-0530-427c-ab36-143a1598e15d.png">

[demo](https://stackblitz.com/edit/react-1pupqw?file=src/App.tsx)

**Comment by 3lang3** [comment]
尝试添加泛型参数，不知道会不会有问题。还需要测试

**Comment by 3lang3** [comment]
release on [2.0.0-alpha.34](https://www.npmjs.com/package/react-vant/v/2.0.0-alpha.34) 🚀
