### ISSUE TITLE
🐛 [Bug]:  Picker 级联选择模式下children为空时渲染异常

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#378]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

2.0.0-alpha.32

### Steps to Reproduce

https://codesandbox.io/s/ji-lian-xuan-ze-forked-8or7qe?file=/App.tsx

### Expected Behavior

children为空时选中二级三级置空

### Actual Behavior

二级三级会显示上一个的子项

**Comment by 3lang3** [comment]
release on [2.0.0-alpha.34](https://www.npmjs.com/package/react-vant/v/2.0.0-alpha.34) 🚀
