### ISSUE TITLE
CountDown 倒计时🐛 [Bug]: onChange回调的currentTime有误，不会变化

### ISSUE THREAD

**Issue by xni220** [3lang3/react-vant#380]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [X] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

2.0

### Steps to Reproduce

CountDown 倒计时🐛 [Bug]: onChange回调的currentTime有误，不会变化

### Expected Behavior

CountDown 倒计时🐛 [Bug]: onChange回调的currentTime有误，不会变化

### Actual Behavior

CountDown 倒计时🐛 [Bug]: onChange回调的currentTime有误，不会变化

**Comment by 3lang3** [comment]
release on [2.0.0-alpha.34](https://www.npmjs.com/package/react-vant/v/2.0.0-alpha.34) 🚀
