### ISSUE TITLE
✨ [Feature]: Dialog ButtonText support React.node

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#389]
### What is the new or updated feature that you are suggesting?

Dialog的ButtonText增加React.node类型支持

### Why should this feature be included?

有个性化的按钮文本需要自定义
<img width="325" alt="image" src="https://user-images.githubusercontent.com/33956589/167243893-a4f4a10b-3be8-4e56-8416-d57916876cd2.png">

**Comment by 3lang3** [comment]
现在应该是支持的，只是类型不对

**Comment by 3lang3** [comment]
close by 0e11d83069f18dca832ce8a81f80f141ad50fc40
