### ISSUE TITLE
[Field] type error

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#39]
**Describe the bug**
`Field` props `onChange` type error
![image](https://user-images.githubusercontent.com/33956589/132615739-b7bc7ff8-85a0-4776-9945-ce2cbfe2f574.png)

**Comment by TinsFox** [comment]
@3lang3 

似乎没有完全修复

![image](https://user-images.githubusercontent.com/33956589/133408418-4478653f-928a-4457-be8d-5a74b56edc77.png)

**Comment by 3lang3** [comment]
@TinsFox 
setTel是不是没指定类型
```ts
const [tel, setTel] = useState('')
// or
const [tel, setTel] = useState<string>()
```

**Comment by TinsFox** [comment]
> @TinsFox
> setTel是不是没指定类型
> 
> ```ts
> const [tel, setTel] = useState('')
> // or
> const [tel, setTel] = useState<string>()
> ```

我记得文档更新了的，怎么又回去了
![image](https://user-images.githubusercontent.com/33956589/133412628-6a923cdd-380a-4486-b683-92956a1a23a3.png)

**Comment by 3lang3** [comment]
我只更新了demo，没更新.md文件
要不你改下？

**Comment by 3lang3** [comment]
fix by #77
