### ISSUE TITLE
🐛 [Bug]: Cascader IOS滚动穿透

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#394]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

2.0.0-alpha.22

### Steps to Reproduce

Cascader 数据太多的时候在IOS上会呈现

### Expected Behavior

正常滚动，不要穿透

### Actual Behavior

会滚动穿透

**Comment by 3lang3** [comment]
@TinsFox 可以更新下试试 还有没有这个问题

**Comment by TinsFox** [comment]
> @TinsFox 可以更新下试试 还有没有这个问题

ok 我找时间试一下

**Comment by 3lang3** [comment]
可以试试v3还有没有这个问题，有再打开吧
