### ISSUE TITLE
[Field] A component is changing an uncontrolled input to be controlled.

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#40]
**Describe the bug**
直接进入使用 Field 组件的页面 输入值会报错

**To Reproduce**
```bash
git clone https://github.com/TinsFox/next-reavt-vant.git
cd next-reavt-vant
yarn && yarn run dev
```
浏览器访问 `http://localhost:7000/field` 迅速输入手机号等

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/33956589/132616246-8a7e1af3-0651-475a-bae2-31c810174af1.png)

**Comment by 3lang3** [comment]
@TinsFox 

https://github.com/TinsFox/next-reavt-vant/blob/4fb67044fee9014433ae8a19d8a85e315698f6b2/pages/field.tsx#L7-L9

这里的`setState`没有给初始值

我demo里面之前也有这个问题 😥

先已经修复

**Comment by 3lang3** [comment]
`setState('')`
