### ISSUE TITLE
🐛 [Bug]: The icon on the right side of the <Collapse /> component is in an abnormal state

### ISSUE THREAD

**Issue by class-undefined** [3lang3/react-vant#402]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

v2.0.0-alpha.37

### Steps to Reproduce

When I specify the className of the <Collapse /> component, the icon on the right does not meet expectations.
Example: https://codesandbox.io/s/autumn-meadow-1j4zz1

I found that it is caused by not handling the className correctly, when the className is specified, the <Collapse /> component will not maintain its className correctly when it performs the action of shrinking/expanding.

### Expected Behavior

The icon should change with the collapsed/expanded state of the <Collapse /> component.

### Actual Behavior

When I specify the className, the icon doesn't change anything.

**Comment by 3lang3** [comment]
收到

**Comment by 3lang3** [comment]
release on [2.0.0-alpha.38](https://www.npmjs.com/package/react-vant/v/2.0.0-alpha.38) 🚀
