### ISSUE TITLE
🐛 [Bug]: Area组件拖动值内容总是回到上次的位置

### ISSUE THREAD

**Issue by Richardend** [3lang3/react-vant#412]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

^2.0.0-alpha.38

### Descripition

cra 5.0.1
按文档上使用Area组件, 改变第一个column的值, 第二个column不会跟着变. 下次才变, 并且第一个column的值也会回弹到 上次的选择; 并且onChange中接收到的值也是上一次的

**Comment by 3lang3** [comment]
@Richardend 能提供一个codesandbox的demo吗
我本地没复现出来

**Comment by 3lang3** [comment]
https://codesandbox.io/s/ji-chu-yong-fa-forked-6rxw6k  没发现问题

**Comment by Richardend** [comment]
感谢回复, 也许是我工程问题
1. 我创建全新的工程, 使用   create-react-app cra-vant  --template typescript  
2. 我的cra 版本 5.0.1
3. 安装react-vant, 命令 npm i react-vant@next.    package.json中为: "react-vant": "^2.0.0-alpha.38",
4. 打印出来的值总是上一次的值. 我看了源码, 下面也是用Picker实现的. 所以我直接使用picker组件 也有相同问题
`import React from 'react';
import './App.css';
import { Picker } from 'react-vant'

type PickerColumn = {
  values: string[];
  defaultIndex: number;
};

const test: PickerColumn[] = [
  {
    values: ['1', '2', '3', '4', '5'],
    defaultIndex: 0
  },
  {
    values: ['a', 'b', 'c', 'd'],
    defaultIndex: 0
  },
];

function App() {
  return (
    <div className="App">
      <Picker
        columns={test}
        title="选择所在地"
        onChange={(c: string, i: number) => console.log(c, i)}
      />
    </div>
  );
}

export default App;`

辛苦您了~!

**Comment by 3lang3** [comment]
@Richardend 要不直接把这个项目传上来吧 我拉下来看下

**Comment by 3lang3** [comment]
按照你的步骤试了下 还是复现不出来，你看下node_modules/react-vant/package.json 是什么版本

**Comment by Richardend** [comment]
https://gitee.com/mr19830707/cra-vant.git  大佬看看这个能下载吗.  浪费你时间了哈;
node_modules/react-vant/package.json里的版本 
  "_from": "react-vant@^2.0.0-alpha.38",
  "_id": "react-vant@2.0.0-dev.30-8",
  "version": "2.0.0-dev.30-8"

我本地node版本 14.18.1

**Comment by 3lang3** [comment]
@Richardend 安装的版本错了， 你删掉node_modules, 重新 yarn add react-vant@next

**Comment by 3lang3** [comment]
上面看你实际装的是 2.0.0-dev.30-8 装了一个开发测试版本

**Comment by Richardend** [comment]
好的, 我再试试

**Comment by 3lang3** [comment]
ok 等你回复

**Comment by 3lang3** [comment]
react 18下复现

**Comment by 3lang3** [comment]
@Richardend 已修复
