### ISSUE TITLE
🐛 [Bug]: react@18 使用Toast报错

### ISSUE THREAD

**Issue by lxdaixin128** [3lang3/react-vant#418]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

v2.0.0

### Descripition

控制台报： Warning: ReactDOM.render is no longer supported in React 18.

**Comment by 3lang3** [comment]
收到！这个马上会修复哈

**Comment by 3lang3** [comment]
@all-contributors please add @lxdaixin128  to bug
