### ISSUE TITLE
ImagePreview 组件调用，如何改变挂载点

### ISSUE THREAD

**Issue by zoujpxyz2017** [3lang3/react-vant#422]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

2.0.0-alpha.39

### Descripition

ImagePreview 组件调用，如何改变挂载点，teleport={document.getElementById('#root') as HTMLElement} 指定这个也不生效

**Comment by zoujpxyz2017** [comment]
追加一个问题：图片预览单击时可以设置是否关闭图片，因为想通过关闭按钮才关闭。beforeClose这个事件两种都会触发

**Comment by zoujpxyz2017** [comment]
还有：如果用到了overlay，ImagePreview 也有这个问题
.rv-swiper-item {
  display: flex !important;
}
.rv-swiper {
  height: 100% !important;
}

需要加上这两个才能够解决图片居中的情况，不知道是否是bug

**Comment by 3lang3** [comment]
> 追加一个问题：图片预览单击时可以设置是否关闭图片，因为想通过关闭按钮才关闭。beforeClose这个事件两种都会触发

这个我加个属性吧

**Comment by 3lang3** [comment]
> 还有：如果用到了overlay，ImagePreview 也有这个问题 .rv-swiper-item { display: flex !important; } .rv-swiper { height: 100% !important; }
> 
> 需要加上这两个才能够解决图片居中的情况，不知道是否是bug

我测下

**Comment by 3lang3** [comment]
@all-contributors please add @zoujpxyz2017 to bug

**Comment by 3lang3** [comment]
@zoujpxyz2017 已发布 🚀 [2.0.0-alpha.41](https://www.npmjs.com/package/react-vant/v/2.0.0-alpha.41)
