### ISSUE TITLE
🐛 [Bug]: 日期选择器滚动异常

### ISSUE THREAD

**Issue by SingleShadow** [3lang3/react-vant#425]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [X] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

^2.0.0-alpha.32

### Descripition

https://codesandbox.io/s/5gf01u?resolutionWidth=320&resolutionHeight=675&file=/App.tsx

日期选择器滚动异常：
在src/index文件中，
import ReactDOM from 'react-dom/client'
import App from './App';
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
      <App >
   </React.StrictMode>
);
使用react18加载项目的话，datetime-picker#搭配弹出层使用这个demo的滚动会有问题

滚动正常：
import ReactDOM from 'react-dom';
import App from './App';
ReactDOM.render(
  <App >,
  document.querySelector('#root'),
);
使用这种方式的话就是正常的

**Comment by 3lang3** [comment]
感谢反馈，上次社区也有反馈类似问题，一直没法复现，这个我会尽快解决

**Comment by 3lang3** [comment]
@all-contributors please add @SingleShadow to bug

**Comment by 3lang3** [comment]
@SingleShadow 已发布 🚀  [2.0.0-alpha.41](https://www.npmjs.com/package/react-vant/v/2.0.0-alpha.41)
