### ISSUE TITLE
🐛 [Bug]: 错别字

### ISSUE THREAD

**Issue by lanten** [3lang3/react-vant#438]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

master

### Descripition

我正在抄写代码，瞧瞧我发现了什么？

由于不是正常单词，cSpell 抛出了警告， 应该是少个p

https://github.com/3lang3/react-vant/blob/1479f53a362110705f3b57f82b1d3bc1de7b010b/packages/react-vant/src/components/popup/PropsType.ts#L59

descrition >  description

**Comment by 3lang3** [comment]
ha~ can you pr for this?

**Comment by 3lang3** [comment]
@all-contributors please add @lanten  to doc

**Comment by 3lang3** [comment]
@lanten 已发布 🚀 [2.0.0-alpha.45](https://www.npmjs.com/package/react-vant/v/2.0.0-alpha.45)
