### ISSUE TITLE
🐛 [Bug]: Field 添加clearable属性，清除图标不显示(umi)

### ISSUE THREAD

**Issue by wgmGithub20** [3lang3/react-vant#442]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

2.0.0-alpha.38

### Descripition

Field 添加clearable属性，清除图标不显示

**Comment by 3lang3** [comment]
@wgmGithub20 能提供复现demo吗 我测了下 没发现问题

**Comment by wgmGithub20** [comment]
> @wgmGithub20 能提供复现demo吗 我测了下 没发现问题

import { ShopO, WarningO } from "@react-vant/icons";
import React, { useState } from "react";
import { Cell, Field, Toast } from "react-vant";

export default () => {
  const [value1, setValue1] = useState("");
  const [value2, setValue2] = useState("");

  return (
    <>
      <Cell.Group>
        <Field
          value={value1}
          onChange={setValue1}
          label="文本"
          leftIcon={<ShopO />}
          rightIcon={<WarningO />}
          placeholder="显示图标"
          onClickLeftIcon={() => Toast.info("左侧图标点击")}
          onClickRightIcon={() => Toast.info("右侧图标点击")}
        />
        <Field
          value={value2}
          onChange={setValue2}
          clearable
          label="文本"
          leftIcon={<ShopO />}
          placeholder="显示清除图标"
        />
      </Cell.Group>
    </>
  );
};

**Comment by 3lang3** [comment]
@wgmGithub20 
https://codesandbox.io/s/ji-chu-yong-fa-forked-3c5hlc?file=/App.jsx

还是没复现出来

**Comment by wgmGithub20** [comment]
> 

在官方文档以及您的链接来看是正常的，但是实际使用会有问题。下面是我的具体复现步骤：

安装umi脚手架: yarn create @umijs/umi-app
安装react-vant： yarn add react-vant@next
使用官方文档示例：

import { ShopO, WarningO } from '@react-vant/icons';
import React, { useState } from 'react';
import { Cell, Field, Toast } from 'react-vant';

export default () => {
  const [value1, setValue1] = useState('');
  const [value2, setValue2] = useState('');

  return (
    <>
      <Cell.Group>
        <Field
          value={value1}
          onChange={setValue1}
          label="文本"
          leftIcon={<ShopO />}
          rightIcon={<WarningO />}
          placeholder="显示图标"
          onClickLeftIcon={() => Toast.info('左侧图标点击')}
          onClickRightIcon={() => Toast.info('右侧图标点击')}
        />
        <Field
          value={value2}
          onChange={setValue2}
          clearable
          label="文本"
          leftIcon={<ShopO />}
          placeholder="显示清除图标"
        />
      </Cell.Group>
    </>
  );
};

运行项目后： clearable图标不显示，达不到预期效果

**Comment by wgmGithub20** [comment]
> @wgmGithub20 https://codesandbox.io/s/ji-chu-yong-fa-forked-3c5hlc?file=/App.jsx
> 
> 还是没复现出来

在官方文档以及您的链接来看是正常的，但是实际使用会有问题。下面是我的具体复现步骤：

安装umi脚手架: yarn create @umijs/umi-app
安装react-vant： yarn add react-vant@next
使用官方文档示例：

import { ShopO, WarningO } from '@react-vant/icons';
import React, { useState } from 'react';
import { Cell, Field, Toast } from 'react-vant';

export default () => {
const [value1, setValue1] = useState('');
const [value2, setValue2] = useState('');

return (
<>
<Cell.Group>
<Field
value={value1}
onChange={setValue1}
label="文本"
leftIcon={}
rightIcon={}
placeholder="显示图标"
onClickLeftIcon={() => Toast.info('左侧图标点击')}
onClickRightIcon={() => Toast.info('右侧图标点击')}
/>
<Field
value={value2}
onChange={setValue2}
clearable
label="文本"
leftIcon={}
placeholder="显示清除图标"
/>
</Cell.Group>
</>
);
};

运行项目后： clearable图标不显示，达不到预期效果

**Comment by wgmGithub20** [comment]
![不显示](https://user-images.githubusercontent.com/62601616/170957163-61825276-2950-4933-96d9-6f29617fde89.png)
![清除图标不显示1](https://user-images.githubusercontent.com/62601616/170957188-e6ac79a9-d771-42e3-ab0a-7b1459ad15c8.png)

**Comment by 3lang3** [comment]
@wgmGithub20 找到原因了哈

![image](https://user-images.githubusercontent.com/7098719/170971466-4961487f-581d-42f6-b0e5-50d4e6d2a1f8.png)

umi内部引入了antd的default.less(应该是内部dev runtime 引入了antd的组件)

可以先用global的形式给 `rv-field__clear `追加个 样式 `box-sizing: content-box;`

**Comment by 3lang3** [comment]
@wgmGithub20 已发布 🚀 [2.0.0-alpha.45](https://www.npmjs.com/package/react-vant/v/2.0.0-alpha.45)

**Comment by AdonLee** [comment]
@3lang3 v3版的Input也出现这个问题~~~

**Comment by 3lang3** [comment]
> @3lang3 v3版的Input也出现这个问题~~~

v3 按上面方法能解决吗

**Comment by AdonLee** [comment]
@3lang3 可以

**Comment by 3lang3** [comment]
> @3lang3 可以

OK
 那打开这个，修复下，popup 图片 lazyload问题我没复现出来，你再看下？
