### ISSUE TITLE
🐛 [Bug]: tab位置错乱

### ISSUE THREAD

**Issue by mu-qing** [3lang3/react-vant#449]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

2.0.0-alpha.39

### Reproduce live demo(codesandebox or stackblitz)?

no

### Descripition

<img width="500" alt="WeChat9d4ba6f0ea3d6c1b82eec8747276701c" src="https://user-images.githubusercontent.com/18158725/171359838-445952f9-6128-4004-a334-a923f1247b9d.png">
![image](https://user-images.githubusercontent.com/18158725/171360199-74a59043-aec1-43c2-915c-9811f903b5ba.png)

当我用在Space组件内嵌使用这个组件时，会发生位置错乱

**Comment by 3lang3** [comment]
@mu-qing 根据你返回的信息我没有复现出来 
https://codesandbox.io/s/ji-chu-yong-fa-forked-md683e?file=/App.jsx

方便使用上面代码复现下吗？

**Comment by 3lang3** [comment]
长时间未回应，未提供复现代码
