### ISSUE TITLE
[Rate] `allow-half` not invalid

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#45]
**Describe the bug**

半星属性不生效

**Screenshots**
![image](https://user-images.githubusercontent.com/33956589/132632764-6cc4f38f-48c8-4efc-8097-37024d7235e5.png)
![image](https://user-images.githubusercontent.com/33956589/132632778-b5c47d20-87f2-4866-a8d0-41a7eb92239c.png)

**Comment by 3lang3** [comment]
是`allowHalf`

**Comment by 3lang3** [comment]
https://github.com/3lang3/react-vant/blob/8913c24eb143e5df3d69b16df65032bff3352ce7/src/rate/PropsType.ts#L24

**Comment by TinsFox** [comment]
demo 背锅 🌚
![image](https://user-images.githubusercontent.com/33956589/132640321-75f59a68-80d2-400d-b891-7ad6d0c7b8ba.png)
