### ISSUE TITLE
✨ [Feature]: v1 中是否考虑增加 FloatingBall 悬浮球? (Add FloatingBall component to v1 version?)

### ISSUE THREAD

**Issue by hacker0limbo** [3lang3/react-vant#451]
### What is the new or updated feature that you are suggesting?

v1 中是否考虑加入 FloatingBall 悬浮球组件?

Any chance to consider adding FloatingBall component to version v1?

### Why should this feature be included?

首先感谢这么优秀的移动端组件库.
我目前是用的 v1, 在 v2 dev 文档里发现有 FloatingBall 悬浮球组件, 虽然当前是 beta 版但效果看上去很不错. 由于个人原因暂时不能升级到 v2 dev 版, 因此想咨询一下是否可能在 v1 中就加入这个组件, 到时候正式发布 v2 之后也能做到无缝升级?

First of all thanks for creating this excellent component library.
I am currently using version1. I found in version2 docs, react-vant added a new component called FloatingBall, which looks good to me so far even though it is still in beta version. Due to personal issue i am not able to upgrade and migrate to version2(dev version). So i am wondering if there is any chance to add this component to version1 so that later after officially releasing version2 we can do migration and upgrading more smoothly?

**Comment by 3lang3** [comment]
假期后我看下，应该可以迁移到v1的，v1升级v2其实br很少的，但无奈文档还没出来。

另外，感谢支持。

**Comment by hacker0limbo** [comment]
@3lang3 好的, 多谢
