### ISSUE TITLE
🐛 [Bug]: 使用Field，在Umi(webpack)构建打包后会有样式异常/覆盖问题

### ISSUE THREAD

**Issue by wgmGithub20** [3lang3/react-vant#460]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

react-vant 2.0.0-alpha.45

### Descripition

使用Field，在打包后会有样式异常/覆盖问题，见下图
![image](https://user-images.githubusercontent.com/62601616/172562625-1b1aa15e-b867-4546-b9e3-287586486fcf.png)

![image](https://user-images.githubusercontent.com/62601616/172562669-bdf93e52-a2fa-421e-98a0-3d7fd817f9b7.png)

**Comment by wgmGithub20** [comment]
我这边暂时解决方案是覆盖样式：
.rv-cell__title {
      flex: none;
 }
希望后续大佬可以优化这个问题

**Comment by 3lang3** [comment]
> 我这边暂时解决方案是覆盖样式： .rv-cell__title { flex: none; } 希望后续大佬可以优化这个问题

收到， 你是用的umi构建吗？

**Comment by wgmGithub20** [comment]
> Reference

是的哈，umi3的

**Comment by wgmGithub20** [comment]
> > 我这边暂时解决方案是覆盖样式： .rv-cell__title { flex: none; } 希望后续大佬可以优化这个问题
> 
> 收到， 你是用的umi构建吗？

是的哈，umi3的

**Comment by 3lang3** [comment]
> > > 我这边暂时解决方案是覆盖样式： .rv-cell__title { flex: none; } 希望后续大佬可以优化这个问题
> > 
> > 
> > 收到， 你是用的umi构建吗？
> 
> 是的哈，umi3的

收到
