### ISSUE TITLE
✨ [Feature]: CheckboxGroup Props add `min`

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#467]
### What is the new or updated feature that you are suggesting?

增加`min` props

### Why should this feature be included?

问卷场景下会有最少选择x个选项，最多选择x个选项

**Comment by 3lang3** [comment]
新增 `min` `max` 选项？

**Comment by TinsFox** [comment]
> 新增 `min` `max` 选项？

`max` 已经有了，加个`min`就行，但是 {max:0}需要改一下，应该是默认可以无限选择数量

**Comment by 3lang3** [comment]
`min` 特性不是很好内置，一般场景应该是在form中通过rule去校验，有什么好的思路吗？

> 但是 {max:0}需要改一下，应该是默认可以无限选择数量

这句没看懂，现在不设置 `max` 就是不限制选择数量啊

**Comment by TinsFox** [comment]
> `min` 特性不是很好内置，一般场景应该是在form中通过rule去校验，有什么好的思路吗？
> 
> > 但是 {max:0}需要改一下，应该是默认可以无限选择数量
> 
> 这句没看懂，现在不设置 `max` 就是不限制选择数量啊



max | 最大可选数，0为无限制 | number \| string | 0
-- | -- | -- | --


现在是这样的，感觉这个0有点歧义，即使是默认值为0内部处理

**Comment by TinsFox** [comment]
目前还没啥思路，antd 也是用rule去校验的，但是交互上来说不太到位。想要的交互是如果限制选择三个，总的选择项有五个，那么在选了三个之后其他两个就disabled掉。用rule去限制的话就只能报error出来，但是还是可以选择三个以上

**Comment by 3lang3** [comment]
> 目前还没啥思路，antd 也是用rule去校验的，但是交互上来说不太到位。想要的交互是如果限制选择三个，总的选择项有五个，那么在选了三个之后其他两个就disabled掉。用rule去限制的话就只能报error出来，但是还是可以选择三个以上

你这个是 `max` 的思路，可以实现，`min` 呢？

**Comment by 3lang3** [comment]
`max` 的默认值其实内部不是0 我调整下文档
