### ISSUE TITLE
🐛 [Bug]: 当Form.Item里面仅有个一个Field组件，Field组件不触发click事件

### ISSUE THREAD

**Issue by AdonLee** [3lang3/react-vant#468]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

1.4.18

### Reproduce live demo(codesandebox or stackblitz)?

https://codesandbox.io/s/an-niu-lei-xing-forked-rf6rme?file=/App.tsx

### Descripition

给Field包一层空组件可以避开这个问题

**Comment by 3lang3** [comment]
是v1版本吗？ 我看demo里面是v1
