### ISSUE TITLE
🐛 [Bug]: Tabs Events 的onScroll参数top滚动时不生效，一直是0

### ISSUE THREAD

**Issue by xni220** [3lang3/react-vant#469]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

2.0

### Descripition

滚动了=> {scrollTop: 0, isFixed: false}
滚动了=> {scrollTop: 0, isFixed: false}

**Comment by 3lang3** [comment]
duplicate #470
