### ISSUE TITLE
[Uploader] prop type errod

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#47]
**Describe the bug**

API Props 类型错误

**Screenshots**
![image](https://user-images.githubusercontent.com/33956589/132637113-919d18ff-d678-44da-bad6-b070a57e92ed.png)

![image](https://user-images.githubusercontent.com/33956589/132637171-88e1a890-6db7-421d-9dc2-15998d79159c.png)

**Comment by 3lang3** [comment]
需要给`useState`类型定义

demo已经更新

```tsx
import type { UploaderFileListItem } from 'react-vant';

const [demo, setDemo] = useState<UploaderFileListItem[]>([
    {
      url: 'https://img.yzcdn.cn/vant/leaf.jpg',
      status: 'uploading',
      message: '上传中...',
    },
    {
      url: 'https://img.yzcdn.cn/vant/tree.jpg',
      status: 'failed',
      message: '上传失败',
    },
  ]);
```
