### ISSUE TITLE
🐛 [Bug]: Tabs Events 的onScroll参数top滚动时不生效，一直是0

### ISSUE THREAD

**Issue by xni220** [3lang3/react-vant#470]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

2.0

### Descripition

滚动了=> {scrollTop: 0, isFixed: false}
滚动了=> {scrollTop: 0, isFixed: false}滚动了=> {scrollTop: 0, isFixed: false}

**Comment by 3lang3** [comment]
@xni220  https://codesandbox.io/s/biao-qian-lan-gun-dong-forked-6bzjnj?file=/App.jsx

我没复现出来，`onScroll` 仅在 sticky 模式下生效
