### ISSUE TITLE
🐛 [Bug]: Pagination组件的totalItems属性变化无效

### ISSUE THREAD

**Issue by wgmGithub20** [3lang3/react-vant#485]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

react-vant 2.0.0-alpha.46

### Reproduce live demo(codesandebox or stackblitz)?

https://codesandbox.io/s/jian-dan-mo-shi-forked-17nolc?file=/App.jsx:527-537

### Descripition

仅仅是totalItems属性改变时，分页效果无变化；
value和totalItems都改变时，分页效果正常；

**Comment by 3lang3** [comment]
🚀 release on [2.0.0-alpha.47](https://www.npmjs.com/package/react-vant/v/2.0.0-alpha.47)
