### ISSUE TITLE
🐛 [Bug]: 升级到react 18后使用组件的时候会提示TS报错

### ISSUE THREAD

**Issue by For-ever21** [3lang3/react-vant#487]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

^2.0.0-alpha.47

### Descripition

在`React18`下，`vant`的`propsType.d.ts`需要增加`children?: React.ReactNode;`的声明,否则会提示如下的TS错误

![image](https://user-images.githubusercontent.com/23413186/176877994-b9f0a151-b87b-4827-97c1-2e23068b431f.png)

**Comment by 3lang3** [comment]
麻烦确认下项目node_modules/react-vant/package.json 的 version字段是多少

**Comment by 3lang3** [comment]
这个问题之前修复过了，还报错的话 一般是安装错了版本

**Comment by For-ever21** [comment]
> 麻烦确认下项目node_modules/react-vant/package.json 的 version字段是多少

2.0.0-dev.30-8 我知道了，那我同步一下版本，多谢指导
