### ISSUE TITLE
More Vant Components 🚚 

### ISSUE THREAD

**Issue by 3lang3** [3lang3/react-vant#5]
组件会持续更新下去，由于个人精力有限，所以速度可能不会太快，但是如果你有特别急的组件需求，欢迎在此留言，我会第一时间和你联系反馈👏。

推荐回复格式：
```bash
- 组件名称：
- vant链接：
- 额外特性：（如果需要）
```

**Comment by Jairwin-L** [comment]
支持微信小程序？

**Comment by 3lang3** [comment]
> 支持微信小程序？

抱歉 暂不支持，小程序可以直接使用官方维护的weapp-vant

**Comment by 0x219** [comment]
emmm, 刚想准备自己写vant-react，啊这截胡了。

**Comment by 3lang3** [comment]
> emmm, 刚想准备自己写vant-react，啊这截胡了。

说出来你可能不行你的`vant-react`也被人占了 😂

**Comment by 0x219** [comment]
> > emmm, 刚想准备自己写vant-react，啊这截胡了。
> 
> 说出来你可能不行你的`vant-react`也被人占了 😂

🌚 业务比较紧急，我还是先用你的顶顶

**Comment by 3lang3** [comment]
> > > emmm, 刚想准备自己写vant-react，啊这截胡了。
> > 
> > 
> > 说出来你可能不行你的`vant-react`也被人占了 😂
> 
> 🌚 业务比较紧急，我还是先用你的顶顶

请放心食用，包售后

**Comment by mytheart** [comment]
- 组件名称：ImagePreview
- vant链接：https://vant-contrib.gitee.io/vant/#/zh-CN/image
- 额外特性：预览图片时支持缩放；

- 组件名称：Image
- vant链接：https://vant-contrib.gitee.io/vant/#/zh-CN/image
- 额外特性：支持懒加载和缩放；

推荐缩放库：react-prismazoom

**Comment by qiutian00** [comment]
> > 如果只想用到表单相关的组件， 用整个包， 打包后体积会大么？
> 
> 支持tree sharking的build方案只会打包项目用到的.

好的

**Comment by 3lang3** [comment]
> > > 如果只想用到表单相关的组件， 用整个包， 打包后体积会大么？
> > 
> > 支持tree sharking的build方案只会打包项目用到的.
> 
> 好的

现在最新版包内置了tree-sharking，常规架手架都支持了 不需要额外设置

**Comment by TinsFox** [comment]
瀑布流组件考虑支持吗？

**Comment by 3lang3** [comment]
> 瀑布流组件考虑支持吗？

可以支持轻量的瀑布流(伪瀑布流)，或者放入pro项目中去🤔

**Comment by qiutian00** [comment]
> > > > 如果只想用到表单相关的组件， 用整个包， 打包后体积会大么？
> > > 
> > > 
> > > 支持tree sharking的build方案只会打包项目用到的.
> > 
> > 
> > 好的
> 
> 现在最新版包内置了tree-sharking，常规架手架都支持了 不需要额外设置

赞赞赞。
