### ISSUE TITLE
🐛 [Bug]: Tab 组件初始化带动画

### ISSUE THREAD

**Issue by algesthesiah** [3lang3/react-vant#505]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

2.0.0-alpha.46

### Descripition

https://react-vant.3lang.dev/components/tabs
进入官网的 Tab 组件页，然后刷新页面，Tab 组件红色线跳了一下

**Comment by algesthesiah** [comment]
"react-vant": "3.0.0-rc.2",
 也有这个问题

**Comment by 3lang3** [comment]
好的 明天我看下

**Comment by algesthesiah** [comment]
感谢

**Comment by 3lang3** [comment]
> 感谢
> 

红色线跳了一下 是指？ 官网都是蓝色呀

**Comment by 3lang3** [comment]
刚群里讨论下，这里和vant表现确实不一致，我找时间改下，但是只会在v3中发布

**Comment by 3lang3** [comment]
🚀 release on [3.0.0-rc.3](https://www.npmjs.com/package/react-vant/v/3.0.0-rc.3)
