### ISSUE TITLE
🐛 [Bug]: Tabs 组件开启 swipeable，首次向右滑动不会展示第二个标签内容。

### ISSUE THREAD

**Issue by OXXD** [3lang3/react-vant#508]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.0.0-rc.1

### Reproduce live demo(codesandebox or stackblitz)?

https://codesandbox.io/s/tender-buck-wjmyuf?file=/App.tsx:2677-2686

### Descripition

Tabs 组件开启 swipeable，存在 BUG。
1. 首次向右滑动不会展示第二个标签内容
2. 内部 List 组件加载事件会触发多次

![image](https://user-images.githubusercontent.com/1464298/178889453-a20643b3-7a56-4832-a593-2e6e70a41b2d.png)

**Comment by 3lang3** [comment]
🚀 release on [3.0.0-rc.3](https://www.npmjs.com/package/react-vant/v/3.0.0-rc.3)
