### ISSUE TITLE
How to get type from react-vant?

### ISSUE THREAD

**Issue by qinglong-zeng** [3lang3/react-vant#51]
![image](https://user-images.githubusercontent.com/25050827/132652249-04804e71-cdb4-4718-be89-952ab4b62cd2.png)

which file can import this type?

**Comment by qinglong-zeng** [comment]
https://3lang3.github.io/react-vant/#/zh-CN/list

**Comment by TinsFox** [comment]
![image](https://user-images.githubusercontent.com/33956589/132654330-14808de4-cb33-4a9d-955d-7b4f446a23ba.png)

**Comment by qinglong-zeng** [comment]
thank u. I find a way to fixed it.
