### ISSUE TITLE
🐛 [Bug]: Toast无法立即关闭

### ISSUE THREAD

**Issue by U1in** [3lang3/react-vant#511]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

react-vant@1.4.18 

### Reproduce live demo(codesandebox or stackblitz)?

https://codesandbox.io/embed/an-niu-lei-xing-forked-fdqxyi?fontsize=14&hidenavigation=1&theme=dark

### Descripition

Toast组件在React17下无法关闭
Toast can not close in React17

**Comment by 3lang3** [comment]
@U1in  
https://codesandbox.io/embed/an-niu-lei-xing-forked-fdqxyi?fontsize=14&hidenavigation=1&theme=dark

这样不行吗？

**Comment by U1in** [comment]
> @U1in https://codesandbox.io/embed/an-niu-lei-xing-forked-fdqxyi?fontsize=14&hidenavigation=1&theme=dark
> 
> 这样不行吗？

不行，这个toast关不掉😥

**Comment by 3lang3** [comment]
> > @U1in https://codesandbox.io/embed/an-niu-lei-xing-forked-fdqxyi?fontsize=14&hidenavigation=1&theme=dark
> > 这样不行吗？
> 
> 不行，这个toast关不掉😥

搞错链接了，这个试试 https://codesandbox.io/s/an-niu-lei-xing-forked-jebxgw?file=/App.tsx

**Comment by U1in** [comment]
> > > @U1in https://codesandbox.io/embed/an-niu-lei-xing-forked-fdqxyi?fontsize=14&hidenavigation=1&theme=dark
> > > 这样不行吗？
> > 
> > 
> > 不行，这个toast关不掉😥
> 
> 搞错链接了，这个试试 https://codesandbox.io/s/an-niu-lei-xing-forked-jebxgw?file=/App.tsx

可以了，Promise的方式可以。我这个依赖版本只能这样子关闭toast吗？需要升级到什么版本可以使用Toast.clear()

**Comment by U1in** [comment]
> > > @U1in https://codesandbox.io/embed/an-niu-lei-xing-forked-fdqxyi?fontsize=14&hidenavigation=1&theme=dark
> > > 这样不行吗？
> > 
> > 
> > 不行，这个toast关不掉😥
> 
> 搞错链接了，这个试试 https://codesandbox.io/s/an-niu-lei-xing-forked-jebxgw?file=/App.tsx

很感谢这么及时的反馈

**Comment by 3lang3** [comment]
> > > > @U1in https://codesandbox.io/embed/an-niu-lei-xing-forked-fdqxyi?fontsize=14&hidenavigation=1&theme=dark
> > > > 这样不行吗？
> > > 
> > > 
> > > 不行，这个toast关不掉😥
> > 
> > 搞错链接了，这个试试 https://codesandbox.io/s/an-niu-lei-xing-forked-jebxgw?file=/App.tsx
> 
> 可以了，Promise的方式可以。我这个依赖版本只能这样子关闭toast吗？需要升级到什么版本可以使用Toast.clear()

哪个版本都是这样啊，你这打开就关是啥需求
