### ISSUE TITLE
🐛 [Bug]: flex default export error

### ISSUE THREAD

**Issue by JasonChen-Spotec** [3lang3/react-vant#515]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

v3.0.0-r3

### Descripition

import './style/index.less';
import _Flex from './Flex';
import FlexItem from './FlexItem';

const Flex = Object.assign(_Flex, { Item: FlexItem });
export { Flex };
export type { FlexProps, FlexItemProps } from './PropsType';

It should be `export default Flex `?

**Comment by 3lang3** [comment]
@JasonChen-Spotec 实际上不需要导出默认值
除非你希望这样引入
```js
import Flex from 'react-vant/components/flex'
```

**Comment by JasonChen-Spotec** [comment]
@3lang3, 谢谢答复, 只是觉得每个单独组件导出行为不一致， 有的组件写了export default, 有的没有。 最开始项目使用了`babel-plugin-import`， 升级vant之后发现个别组件报错， 原因export方式导致。当然移除babel-plugin-import之后工作正常。  所以看需不需把组件都保持一致移除或者保留export default。

**Comment by 3lang3** [comment]
> @3lang3, 谢谢答复, 只是觉得每个单独组件导出行为不一致， 有的组件写了export default, 有的没有。 最开始项目使用了`babel-plugin-import`， 升级vant之后发现个别组件报错， 原因export方式导致。当然移除babel-plugin-import之后工作正常。  所以看需不需把组件都保持一致移除或者保留export default。

重构过程引起的确实没做到统一哈，后续完善下这块

**Comment by U1in** [comment]
@3lang3 你好，我在react-vant 1x升级到3x的过程中也发现了该问题，提示没有导出默认的组件还有Divider，Search，Empty，Form等。请问这个问题后续是怎么处理的，只能手动按需引用了吗？
