### ISSUE TITLE
🐛 [Bug]: sku组件中的stepper打包时css未加入进去，丢失，导致打包后+-以及输入框无任何样式

### ISSUE THREAD

**Issue by xni220** [3lang3/react-vant#520]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

v3.0.0.0-rc.4

### Descripition

sku组件中的stepper打包时css未加入进去，丢失，导致打包后+-以及输入框无任何样式
[https://dev2-feinibuqu.oss-cn-shenzhen.aliyuncs.com/upfile/renyang/1.1658836008.3118.png](url)

**Comment by 3lang3** [comment]
你项目是什么脚手架

**Comment by xni220** [comment]
{
"private": true,
"scripts": {
"analyze": "cross-env ANALYZE=1 umi build",
"start": "umi dev",
"build": "umi build",
"postinstall": "umi generate tmp",
"prettier": "prettier --write '**/*.{js,jsx,tsx,ts,less,md,json}'",
"test": "umi-test",
"test:coverage": "umi-test --coverage"
},
"gitHooks": {
"pre-commit": "lint-staged"
},
"lint-staged": {
"*.{js,jsx,less,md,json}": [
"prettier --write"
],
"*.ts?(x)": [
"prettier --parser=typescript --write"
]
},
"dependencies": {
***@***.***/pro-layout": "6.31.3",
***@***.***/core": "^2.4.2",
***@***.***/pull-up": "^2.4.2",
***@***.***/use-localstorage": "^2.2.2",
***@***.***/react-tmap": "^0.1.2",
***@***.***/nutui-react": "^1.1.4",
***@***.***/copy": "^2.0.1",
***@***.***/icons": "^0.0.6",
***@***.***/area-data": "^1.2.4",
"ahooks": "^3.3.10",
"babel-plugin-transform-remove-console": "^6.9.4",
"jsonp": "^0.2.1",
"lodash": "^4.17.21",
"postcss-pxtorem": "^5.1.1",
"qrcode.react": "^3.0.2",
"react": "17.0.2",
"react-amap": "^1.2.8",
"react-dom": "17.0.2",
"react-vant": "^3.0.0-rc.4",
"reactjs-localstorage": "^1.0.1",
"umi": "3.5.20",
"umi-plugin-keep-alive": "^0.0.1-beta.30",
"xgplayer": "^2.31.6"
},
"devDependencies": {
***@***.***/react": "17.0.37",
***@***.***/react-dom": "17.0.11",
***@***.***/preset-react": "1.8.30",
***@***.***/test": "3.5.20",
"cross-env": "7.0.3",
"lint-staged": "12.1.2",
"postcss-px-to-viewport": "1.1.1",
"prettier": "2.5.0",
"typescript": "4.5.2",
"yorkie": "2.0.0"
}
}



在 2022-07-26 21:42:46，"3lang" ***@***.***> 写道：

你项目是什么脚手架

**Comment by 3lang3** [comment]
ok 明天我复现下

**Comment by 3lang3** [comment]
@xni220 找到问题了，这两天修复
