### ISSUE TITLE
🐛 [Bug]: Search组件设置actionText时 onCancel事件不触发

### ISSUE THREAD

**Issue by AdonLee** [3lang3/react-vant#523]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.0.0-rc.4

### Reproduce live demo(codesandebox or stackblitz)?

localhost

### Descripition

Search组件设置actionText时 onCancel事件不触发

**Comment by 3lang3** [comment]
@AdonLee  自定义 `actionText` 后，还需要触发 onCancel吗？

调整下 `actionText` 类型好了，变成 `ReactNode | (cancel: () => void) => ReactNode`

**Comment by 3lang3** [comment]
actionText原来就是自定义取消按钮，所以还是直接加上 `onCancel` 好了

**Comment by AdonLee** [comment]
@3lang3 actionText可能需要换个名字，text看上去只是传个文本，而不是ReactNode

**Comment by 3lang3** [comment]
> @3lang3 actionText可能需要换个名字，text看上去只是传个文本，而不是ReactNode

确实
