### ISSUE TITLE
🐛 [Bug]: [v2]Checkbox `style` 不生效

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#524]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

2.0.0-alpha.22

### Descripition

Checkbox 设置style 不生效

```tsx
  <Checkbox defaultChecked checkedColor={'#1B612C'} style={{ display: 'inline-flex' }} />
```

**Comment by 3lang3** [comment]
v2啊？ 那得等等拉

**Comment by 3lang3** [comment]
v2 待修复
