### ISSUE TITLE
🐛 [Bug]: Image lazyload does not work in Popup component

### ISSUE THREAD

**Issue by AdonLee** [3lang3/react-vant#545]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.0.0-rc.7

### Descripition

Image lazyload does not work in Popup

**Comment by 3lang3** [comment]
@AdonLee  我测了下 没复现出来，方便给个live demo吗

**Comment by AdonLee** [comment]
@3lang3 嗯~~应该是我代码的问题，现在好了。。。。
