### ISSUE TITLE
[Bug][Sticky] props type error

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#55]
**Describe the bug**

props type error

**Screenshots**

![image](https://user-images.githubusercontent.com/33956589/132665685-4e533432-12f7-4bd5-959c-bcb57d4dee22.png)

**Comment by 3lang3** [comment]
@TinsFox 

代码没问题，demo代码里面少了类型声明

```tsx
const container = useRef<HTMLElementD>(null);
```

**Comment by TinsFox** [comment]
`const container = useRef<HTMLElementD>(null);`
还是
`const container = useRef<HTMLElement>(null);`

前者 `HTMLElementD`是啥 

后者会报

![image](https://user-images.githubusercontent.com/33956589/132667904-f024ff40-ec9f-48aa-ab4b-a9fae93b8239.png)

![image](https://user-images.githubusercontent.com/33956589/132667926-21700e41-1f54-4d19-a373-00ed5ebbce2a.png)

**Comment by 3lang3** [comment]
不知道怎么打错了。。迷糊了 😂
```tsx
const container = useRef<HTMLDivElement>(null)
```
