### ISSUE TITLE
🐛 [Bug]: Image.iconSize 不生效

### ISSUE THREAD

**Issue by AdonLee** [3lang3/react-vant#566]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.0.0

### Descripition

内部传值传错了

**Comment by 3lang3** [comment]
欢迎pr

**Comment by 3lang3** [comment]
现在 `errorIcon` 和 `loadingIcon` 都支持自定义组件了，`iconSize` 应该可以废除了。

**Comment by a145789** [comment]
看了下 vant vue， iconSize 应该是调节默认的 errorIcon loadingIcon 大小的吧

**Comment by 3lang3** [comment]
> 看了下 vant vue， iconSize 应该是调节默认的 errorIcon loadingIcon 大小的吧

现在这两个都支持自定义组件，iconSize无法完全覆盖自定义组件大小边界了，用户可以自己在组件上定义大小
