### ISSUE TITLE
请求Form 组件支持控制必录星号(*)的显隐

### ISSUE THREAD

**Issue by wgmGithub20** [3lang3/react-vant#574]
### What is the new or updated feature that you are suggesting?

请求Form 组件支持控制必录星号(*)的显隐，谢谢大佬！

### Why should this feature be included?

大部分移动端表单项都没有星号，希望能添加新属性全局控制星号的显隐。

**Comment by 3lang3** [comment]
现在支持required呀 试过吗？

**Comment by wgmGithub20** [comment]
> 



> 现在支持required呀 试过吗？

我意思是 字段必录，但不显示星号。目前必录的字段都带星号，希望在必录状态下也可以控制星号的显隐。

**Comment by 3lang3** [comment]
https://codesandbox.io/s/ji-chu-yong-fa-forked-ib1gol 是这样吗？

**Comment by wgmGithub20** [comment]
> https://codesandbox.io/s/ji-chu-yong-fa-forked-ib1gol 是这样吗？

是这个效果。有点小问题，Form.Item的required属性仅仅是控制星号显隐，但在文档里的说明容易被误解用来控制字段必录。还有，能否在Form 加一个属性统一控制星号显隐呢

**Comment by 3lang3** [comment]
> 

文档确实不够严谨，统一设置可以有，等下次发版吧
