### ISSUE TITLE
✨ [Feature]: Uploader 支持手动指定是否为图片

### ISSUE THREAD

**Issue by maroon1** [3lang3/react-vant#576]
### What is the new or updated feature that you are suggesting?

目前 Uploader 组件通过 URL 是否为图片后缀名来决定是否显示为图片信息，对于有些文件服务器并不会生成带扩展名信息的 URL，此时无法预览图片，建议在 UploaderValueItem 中添加 isImage 可选项，让用户可以显式的指定文件类型

### Why should this feature be included?

有些文件服务器并不会生成带扩展名信息的 URL

**Comment by 3lang3** [comment]
欢迎pr哈😄

**Comment by 3lang3** [comment]
新增 `isImageUrl` 方法，支持此 feature
```jsx
<Upload isImageUrl={() => true} />
```
