### ISSUE TITLE
🐛 [Bug]: Typography disabled 时没有阻止事件

### ISSUE THREAD

**Issue by NoDocCat** [3lang3/react-vant#577]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.0.0

### Reproduce live demo(codesandebox or stackblitz)?

https://codesandbox.io/s/an-niu-lei-xing-forked-pjk1el?file=/App.tsx&resolutionWidth=706&resolutionHeight=675

### Descripition

应在 disabled 时阻止事件触发

**Comment by 3lang3** [comment]
已复现，欢迎pr
