### ISSUE TITLE
🐛 [Feature]: Search 组件右侧为"搜索"按钮更符合常规需求

### ISSUE THREAD

**Issue by wgmGithub20** [3lang3/react-vant#580]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

v3

### Descripition

目前Search组件右侧默认是清除功能，即使是自定义文本为"搜索"，点击后也会自动清空内容，实际上大部分的需求是点击搜索按钮后，还保留原来输入的搜索内容。而且，右侧为"搜索"按钮更符合常规需求。希望大佬能够调整下，谢谢！

**Comment by 3lang3** [comment]
收到收到

**Comment by 3lang3** [comment]
新增 `action` 支持此feature，改原有api会造成breaking change.
