### ISSUE TITLE
🐛 [Bug]: Tabs组件使用sticky属性，ios11报错

### ISSUE THREAD

**Issue by JayHowe** [3lang3/react-vant#581]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [X] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

2.0.0-alpha.47

### Descripition

Tabs组件使用sticky属性，ios11报错：

具体代码：
<Tabs
      sticky
 >
    <Tabs.TabPane>xxx</Tabs.TabPane>
 </Tabs>
 
 报错:
 
 TypeError: r is not a function. (In 'r()' 'r' is null) xxxx

**Comment by 3lang3** [comment]
ios11吗？ 没设备复习，能帮忙定位下问题吗
