### ISSUE TITLE
🐛 [Bug]:  v3.0.3  Error: Cannot find module 'react-vant/bundle/react-vant.js'

### ISSUE THREAD

**Issue by loyep** [3lang3/react-vant#594]
### Which React Vant packages are impacted?

- [x] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.0.3

### Descripition

v3 package.json
```
  "exports": {
    ".": {
      "node": {
        "import": "./bundle/react-vant.es.js",
        "require": "./bundle/react-vant.js"
      },
      "require": "./lib/index.js",
      "import": "./es/index.js",
      "types": "./es/index.d.ts"
    },
    "./es": "./es/index.js",
    "./lib": "./lib/index.js",
    "./es/": "./es/",
    "./lib/": "./lib/",
    "./bundle/": "./bundle/",
    "./2x": "./2x/es/index.js",
    "./2x/": "./2x/",
    "./package.json": "./package.json",
    "./*": "./*"
  }
```

实际发版的目录是
<img width="437" alt="image" src="https://user-images.githubusercontent.com/16043490/200563309-9c706b80-118f-40b0-a91f-b91b86a02fd0.png">

**Comment by 3lang3** [comment]
发版手贱点错script了， 已经修复。
`3.0.3` 已经标记成 `deprecate`
