### ISSUE TITLE
🐛 [Bug]: Tab Prop `style` did not match. Server: "null" Client: "background-color:"

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#595]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.0.2

### Reproduce live demo(codesandebox or stackblitz)?

nextjs 13.0.2

### Descripition

Prop `style` did not match. Server: "null" Client: "background-color:"
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/33956589/201335965-36610a19-7123-4fe7-8984-1e56a1aef3b9.png">

**Comment by 3lang3** [comment]
13还没试过，有时间看下
