### ISSUE TITLE
🐛 [Bug]: 3.0.4版本不支持tree-shaking

### ISSUE THREAD

**Issue by xiejun-net** [3lang3/react-vant#598]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.0.4

### Descripition

```
"react-vant": "^3.0.4",
```
![image](https://user-images.githubusercontent.com/12869626/202396251-d349a52a-c707-4ce4-a4a4-a94d718e111a.png)

**Comment by 3lang3** [comment]
build试过了吗

**Comment by xiejun-net** [comment]
> build试过了吗
Build过了，引用Toast组件会有问题，引用Button组件不会

**Comment by xiejun-net** [comment]
![image](https://user-images.githubusercontent.com/12869626/202452662-1aad3e77-bfa6-4147-bae3-b6e0597d35ac.png)
这是是否引用Toast组件，Home页面对应js的大小对比

**Comment by xiejun-net** [comment]
好吧，我大概知道了，因为Toast组件引用了整个 react-vant/icons

**Comment by 3lang3** [comment]
> 好吧，我大概知道了，因为Toast组件引用了整个 react-vant/icons

icons按理也支持tree shaking的 你退回到3.0.2试试，3.0.4icons有轻微调整  可能影响到了
