### ISSUE TITLE
🐛 [Bug]: List组件加载更多失败后，doLoadMore会重新抛出exception，导致unhandledrejection

### ISSUE THREAD

**Issue by AdonLee** [3lang3/react-vant#604]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.0.0

### Descripition

不要重新抛出exception

**Comment by seame1on** [comment]
同样遇见这个问题，onLoad里请求抛出异常会报错，应该如何将异常传给List组件

**Comment by 3lang3** [comment]
方便给个复现的demo吗
