### ISSUE TITLE
🐛 [Bug]: Space android机中 css gap 有兼容问题 

### ISSUE THREAD

**Issue by xiaoyu311** [3lang3/react-vant#611]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

最新版本

### Descripition

OPPO R11t 中，系统 Android 8.1.0 Space 中 gap 属性未生效

**Comment by 3lang3** [comment]
具体什么浏览器环境？

**Comment by xiaoyu311** [comment]
> 



> 具体什么浏览器环境？

Mozilla/5.0 (Linux; Android 8.1.0; OPPO R11t Build/OPM1.171019.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/62.0.3202.84 Mobile Safari/537.36

**Comment by 3lang3** [comment]
上面浏览器 不支持css属性 `gap`, 暂时无法解决。
