### ISSUE TITLE
🐛 [Bug]: 在Astro中使用，组件的样式没有自动引入

### ISSUE THREAD

**Issue by m-initiator** [3lang3/react-vant#613]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.1.2

### Descripition

在Astro框架中引入了组件
 `import { Button } from 'react-vant';`  
但是按钮没有样式，是没有自动引入样式吗，想知道在Astro框架中如何使用该UI框架。

**Comment by 3lang3** [comment]
我有时间弄个demo吧 思路和remix这类ssr框架应该差不多

**Comment by 3lang3** [comment]
[demo](https://github.com/3lang3/react-vant-template/tree/main/next/astro)，文档稍后更新

**Comment by m-initiator** [comment]
十分感谢

**Comment by m-initiator** [comment]
大佬， 试试build，我这边dev可以运行，build打包失败。

**Comment by 3lang3** [comment]
我抽空看下哈

**Comment by 3lang3** [comment]
> 大佬， 试试build，我这边dev可以运行，build打包失败。

将组件directives改为 `client-only` 可以顺利通过dev和build

```tsx
<Layout title="Welcome to Astro.">
	<ReactVantDemo client:only />
</Layout>
```

**Comment by m-initiator** [comment]
可以了，太感谢了
