### ISSUE TITLE
🐛 [Bug]: icon 没有treeshaking 看着是全部引入了

### ISSUE THREAD

**Issue by xiaojingyuaner** [3lang3/react-vant#618]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

  "react-vant": "^3.0.2"
  

### Descripition
用vite构建
icon 没有treeshaking 看着是全部引入了
![image](https://user-images.githubusercontent.com/24470322/216313704-6b753ede-990f-4197-ad10-accde7041b7a.png)

![image](https://user-images.githubusercontent.com/24470322/216312976-0603791a-5c89-4004-96d1-90fef797b51d.png)

**Comment by 3lang3** [comment]
明天我复现下

**Comment by xiaojingyuaner** [comment]
有效的，感谢
