### ISSUE TITLE
🐛 [Bug]: 能否增加类似antd mobile的FloatingPanel 浮动面板组件?

### ISSUE THREAD

**Issue by Vinsurs** [3lang3/react-vant#619]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.1.4

### Descripition

希望作者能考虑新增类似antd mobile的[FloatingPanel](https://mobile.ant.design/zh/components/floating-panel) 浮动面板组件

**Comment by 3lang3** [comment]
忙于工作，最近实在没精力来新增feature，欢迎pr👏🏻
