### ISSUE TITLE
picker下拉内容为空时，点击取消或者确定报错🐛 [Bug]: 

### ISSUE THREAD

**Issue by drx0811** [3lang3/react-vant#620]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

v1.4.17

### Descripition

picker下拉内容为空时，点击取消或者确定报错

![image](https://user-images.githubusercontent.com/25926797/219248835-ce9370da-8bf3-450a-95e0-0551ca09b0c2.png)

**Comment by 3lang3** [comment]
v1吗？先试试v3有没有这个问题吧，没有的话 我同步到v1好了，或者内容为空是 通过visible关闭？

**Comment by 3lang3** [comment]
https://codesandbox.io/s/qi-yong-dan-chu-ceng-forked-r953lq?file=/App.tsx

v1没有复现出来

**Comment by drx0811** [comment]
> https://codesandbox.io/s/qi-yong-dan-chu-ceng-forked-r953lq?file=/App.tsx
> 
> v1没有复现出来
添加上其它属性

https://codesandbox.io/s/qi-yong-dan-chu-ceng-forked-r953lq?file=/App.tsx

**Comment by 3lang3** [comment]
@drx0811 在 `1.4.19` 版本中修复了
https://codesandbox.io/s/qi-yong-dan-chu-ceng-forked-r953lq?file=/App.tsx
