### ISSUE TITLE
🐛 [Bug]: Dialog 组件调用模式下，onConfirm 返回 Promise 函数无效，无法显示 loading

### ISSUE THREAD

**Issue by tianxing0923** [3lang3/react-vant#624]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.1.4

### Reproduce live demo(codesandebox or stackblitz)?

https://stackblitz.com/edit/react-cvan3u?file=src%2FApp.tsx

### Descripition

Dialog 组件调用模式下，onConfirm 返回 Promise 函数无效，无法显示 loading

**Comment by 3lang3** [comment]
Dialog目前只有函数式调用支持Promise，组件式方式需要自己申明:
```tsx
<Dialog
  confirmProps={{
    loading: true
  }}
/>
```
https://stackblitz.com/edit/react-cvan3u-idh58u?file=src%2FApp.tsx

**Comment by tianxing0923** [comment]
> Dialog目前只有函数式调用支持Promise，组件式方式需要自己申明:
> 
> ```tsx
> <Dialog
>   confirmProps={{
>     loading: true
>   }}
> />
> ```
> 
> https://stackblitz.com/edit/react-cvan3u-idh58u?file=src%2FApp.tsx

好吧，文档中没写有这个配置项，没看源码...
