### ISSUE TITLE
🐛 [Bug]: 输入框input字数限制，输入最后几个字符的时候，无法输入中文

### ISSUE THREAD

**Issue by githubhwen** [3lang3/react-vant#628]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

1.0.0-beta.38

### Descripition

该bug在官网可复现，限制10个字符的输入框，输入9个中文后，最后一个文字在打中文的时候，输入不了
https://react-vant.3lang.dev/components/input#props

**Comment by 3lang3** [comment]
是因为中文会占两个字符

**Comment by luo3house** [comment]
should be a bug 
https://developer.mozilla.org/en-US/docs/web/html/attributes/maxlength
