### ISSUE TITLE
🐛 [Bug]: 引入react-vant中的swipeCell组件会报错

### ISSUE THREAD

**Issue by yrq1429** [3lang3/react-vant#633]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.2.0

### Descripition

Uncaught (in promise) Error: Error: Cannot find module './base-f577a737.css'
![Uploading image.png…]()

**Comment by 3lang3** [comment]
方便给个复现demo吗

**Comment by yrq1429** [comment]
很奇葩的问题。我同事安装之后没问题 然后加了句
import React from 'react';import React from 'react';

跑起来了&nbsp;
然后我重新yarn start又报错...


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "3lang3/react-vant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月15日(星期三) 晚上6:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [3lang3/react-vant] 🐛 [Bug]: 引入react-vant中的swipeCell组件会报错 (Issue #633)





 
方便给个复现demo吗

**Comment by yrq1429** [comment]
![image](https://user-images.githubusercontent.com/35523511/225280212-3f015455-4c8d-469d-a5fc-4af1bb22b46a.png)

依赖里面都没有这个base.less文件？

**Comment by 3lang3** [comment]
删除依赖重新装下试试？

**Comment by 3lang3** [comment]
> 

无法复现，麻烦给出完整的复现步骤

**Comment by yrq1429** [comment]
算了算了 在Taro3.6.1的项目中写的H5页面；我也不好提供代码


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "3lang3/react-vant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月16日(星期四) 下午5:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [3lang3/react-vant] 🐛 [Bug]: 引入react-vant中的swipeCell组件会报错 (Issue #633)





   
无法复现，麻烦给出完整的复现步骤

**Comment by 3lang3** [comment]
react-vant 不支持taro的，你确定用的是这个库？

**Comment by yrq1429** [comment]
我是taro编译的h5项目；这个不支持是吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "3lang3/react-vant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月16日(星期四) 晚上6:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [3lang3/react-vant] 🐛 [Bug]: 引入react-vant中的swipeCell组件会报错 (Issue #633)





 
react-vant 不支持taro的，你确定用的是这个库？

**Comment by 3lang3** [comment]
> 我是taro编译的h5项目；这个不支持是吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "3lang3/react-vant" ***@***.***&gt;; 发送时间:&nbsp;2023年3月16日(星期四) 晚上6:11 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [3lang3/react-vant] 🐛 [Bug]: 引入react-vant中的swipeCell组件会报错 (Issue #633) react-vant 不支持taro的，你确定用的是这个库？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你看下你用的哪个包

**Comment by lawshachMa** [comment]
我也遇到这个问题了，taro + react-vant，确实是不支持taro嘛
![image](https://user-images.githubusercontent.com/122844706/227961390-d3dd752b-1020-4cad-85f5-984a21eeb3a6.png)

**Comment by 3lang3** [comment]
> 我也遇到这个问题了，taro + react-vant，确实是不支持taro嘛 ![image](https://user-images.githubusercontent.com/122844706/227961390-d3dd752b-1020-4cad-85f5-984a21eeb3a6.png)

抱歉，确实不支持
