### ISSUE TITLE
🐛 [Bug]:  input clearable not working

### ISSUE THREAD

**Issue by osmanthustonx** [3lang3/react-vant#634]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

^3.2.4

### Reproduce live demo(codesandebox or stackblitz)?

https://codesandbox.io/s/an-niu-lei-xing-forked-sep6vk?file=/App.tsx:409-414

### Descripition

input 清除按鈕及 onClear 無法運作

**Comment by luo3house** [comment]
Please note that React Vant orients mobile-first, try simulate touch events at desktop: https://react-vant.3lang.dev/guide/advanced-usage#%E8%A7%A6%E6%91%B8%E4%BA%8B%E4%BB%B6%E6%A8%A1%E6%8B%9F

**Comment by osmanthustonx** [comment]
> Please note that React Vant orients mobile-first, try simulate touch events at desktop: https://react-vant.3lang.dev/guide/advanced-usage#%E8%A7%A6%E6%91%B8%E4%BA%8B%E4%BB%B6%E6%A8%A1%E6%8B%9F

thanks dude🥹
