### ISSUE TITLE
🐛 [Bug]:添加PullRefresh 组件后，里面的内容无法进行复制

### ISSUE THREAD

**Issue by nayuta19** [3lang3/react-vant#642]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.2.7

### Descripition

https://react-vant.3lang.dev/components/list
如此案例，基本用法的列表内容可以复制，而添加下拉后的内容无法复制

**Comment by 3lang3** [comment]
桌面端还是移动端？

**Comment by nayuta19** [comment]
> 桌面端还是移动端？

移动端

**Comment by 3lang3** [comment]
> > 桌面端还是移动端？
> 
> 移动端

在ios 16，在chrome和微信浏览器都没复现出来，长按都能弹出选框，建议使用单独的copy逻辑，例如 useCopy
