### ISSUE TITLE
🐛 [Bug]: Dialog组件onClose和onClosed回调触发时机错误

### ISSUE THREAD

**Issue by Garin151** [3lang3/react-vant#645]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.2.7

### Descripition

`
Dialog.confirm({
  title: '标题',
  message: '代码是写出来给人看的，附带能在机器上运行',
  onConfirm: () => {},
  onCancel: () => {},
  onClose: console.log('close'),
  onClosed: console.log('closed'),
 });
`
如上所示，onClose和onClosed回调，没有在弹窗关闭时触发，反而在弹窗出现时触发

**Comment by 3lang3** [comment]
好兄弟 你代码写错了
```tsx
Dialog.confirm({
            title: '标题',
            message: '代码是写出来给人看的，附带能在机器上运行',
            onClose: () => console.log('close'), 
            onClosed: () => console.log('closed')
          })
```

**Comment by 3lang3** [comment]
你写的是 `onClose: console.log('close')`
