### ISSUE TITLE
✨ [Feature]: Radio支持脱离Group使用

### ISSUE THREAD

**Issue by southorange0929** [3lang3/react-vant#648]
### What is the new or updated feature that you are suggesting?

https://github.com/3lang3/react-vant/blob/main/packages/react-vant/src/components/radio/Radio.tsx#L29

目前看脱离Group好像无法单独选中。不知道是这么设计的还是说实现有问题

### Why should this feature be included?

支持单独使用Radio进行选中

**Comment by 3lang3** [comment]
就是这么设计的哈，你的场景是不是用 `Checkbox` 或者 `Switch` 更合适？

**Comment by southorange0929** [comment]
😯我看到了。如果`checkbox`支持的自定义图标的话 应该也是可以的。其实就是一个类似于签署协议的选项，如果这样设计的话。可以考虑对TS定义进行优化，把radio对`checked`等属性的声明Omit掉

**Comment by 3lang3** [comment]
> 😯我看到了。如果`checkbox`支持的自定义图标的话 应该也是可以的。其实就是一个类似于签署协议的选项，如果这样设计的话。可以考虑对TS定义进行优化，把radio对`checked`等属性的声明Omit掉

`Checkbox` 支持自定义图标的

关于 `Radio` ts定义 确实可以优化

**Comment by yaodongyi** [comment]
3.3.4版本，为什么无法使用？
<img width="884" alt="image" src="https://github.com/3lang3/react-vant/assets/31060569/81d2d30a-fd42-452e-ba1e-c8a319bb7b79">
