### ISSUE TITLE
🐛 [Bug]: Picker第一个节点没有children导致级联失效

### ISSUE THREAD

**Issue by a6930216745** [3lang3/react-vant#652]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.2.7

### Reproduce live demo(codesandebox or stackblitz)?

https://stackblitz.com/edit/stackblitz-starters-xmazgj

### Descripition

![image](https://github.com/3lang3/react-vant/assets/28619389/42948ca5-ead5-42a4-90b4-32b719d0e5f4)

**Comment by 3lang3** [comment]
兄弟江苏省成自治市啦😄

**Comment by a6930216745** [comment]
> 兄弟江苏省成自治市啦😄

我这里实际用的是自定义类型树
