### ISSUE TITLE
✨ [Feature]: 有没有React-vant 的 cdn 版本可用？

### ISSUE THREAD

**Issue by xiaojingyuaner** [3lang3/react-vant#657]
### What is the new or updated feature that you are suggesting?

有没有React-vant 的 cdn 版本可用？

### Why should this feature be included?

有没有React-vant 的 cdn 版本可用？

**Comment by 3lang3** [comment]
https://github.com/3lang3/react-vant-template/tree/main/next/html

看下这个

**Comment by xiaojingyuaner** [comment]
感谢～
