### ISSUE TITLE
🐛 [Bug]: ActionSheet在umijs 4.0.72 里控制台报错

### ISSUE THREAD

**Issue by 1316346949** [3lang3/react-vant#659]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.3.1

### Descripition

![image](https://github.com/3lang3/react-vant/assets/24400797/8fb3ebdc-51c2-4022-9468-f3d7548aa9c0)
![image](https://github.com/3lang3/react-vant/assets/24400797/d54dbfca-3063-4150-ace7-f88f05c3e20b)
![image](https://github.com/3lang3/react-vant/assets/24400797/034803ae-00a1-493d-befb-a041a140e569)

**Comment by 1316346949** [comment]
功能是可以使用的，但是控制台会出现错误

**Comment by 3lang3** [comment]
好的👌🏻

**Comment by light212** [comment]
解决了吗

**Comment by light212** [comment]
我解决了这个问题https://github.com/3lang3/react-vant/issues/677
