### ISSUE TITLE
🐛 [Bug]: DatetimePicker在Form中，onConfirm返回的value错误

### ISSUE THREAD

**Issue by xiaolong233** [3lang3/react-vant#663]
### Which React Vant packages are impacted?

- [x] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.3.1

### Descripition

`DatetimePicker`组件在`Form`组件中，以`Popup`的方式被调用。此时，如果把`Form.Item`的`trigger`设置为`onoConfirm`时，返回的`value`不是用户选择的日期。  
通过监听`DatetimePicker`组件的`onChange`和`onConfirm`事件发现，如果不设置`Form.Item`的`trigger`时，`onConfirm`返回的`value`是正确的，但如果设置为`onoConfirm`时，则返回的`value`时错误的。
```
const [form] = Form.useForm();
......
<Form form={form} onFieldsChange={(values) => console.log(values)}>
    <Form.Item 
            name="beginDate" 
            label="起保日期" 
            isLink 
            trigger="onConfirm" 
            onClick={(e, ref) => { 
                   ref?.current?.open(); 
            }}
    >
        <DatetimePicker 
                title="选择起保日期" 
                type="date" 
                popup 
                onChange={(value: Date) => console.log(value)} 
                onConfirm={(value: Date) => console.log(value)}
        >
                {(value: Date) => (value ? moment(value).format('yyyy-MM-DD') : '请选择起保日期')}
        </DatetimePicker>
    </Form.Item>
</Form>
```
**效果图：**
![1](https://github.com/3lang3/react-vant/assets/22933134/a66eb380-2324-4cba-9dd5-0651911eaf01)
**调试输出：**
![2](https://github.com/3lang3/react-vant/assets/22933134/6504abf2-48a3-44ae-9e15-d086d72af74d)

**Comment by day-xue** [comment]
感觉可以包一层 把传下来的onchange 事件在onConfirm 调用一次
