### ISSUE TITLE
🐛 [Bug]: 没有办法自动引入vant任何组件

### ISSUE THREAD

**Issue by yaodongyi** [3lang3/react-vant#666]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

 "react-vant": "^3.3.1"

### Descripition

<img width="516" alt="image" src="https://github.com/3lang3/react-vant/assets/31060569/cd63829b-c77b-4853-9e45-35e30581f965">

1. 我确认我配置正常，使用别的框架是能够正常引用。
2. 使用的是react 17

**Comment by yaodongyi** [comment]
目前使用只能手动import 很难受

**Comment by day-xue** [comment]
react 不都这样？😂
