### ISSUE TITLE
🐛 [Bug]: <GridItem>组件icon失效

### ISSUE THREAD

**Issue by Quokka-CQ** [3lang3/react-vant#667]
### Which React Vant packages are impacted?

- [x] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.3.1

### Descripition

在NextJS中使用react-vant
`list中的icon形如icon: '/creditcard/apply.png'`，
以下为出错代码
`         {list.map(({ icon, typename, type }, index) => (
          <GridItem
            key={index}
            icon={<Image src={icon} width={60} height={60} alt="..."></Image>}
            text={typename}
            onClick={(e) => {
              onClickGridItem(type, typename)
            }}>
            {typename}
          </GridItem>
        ))}
`
按此方法使用，icon在页面中不显示，且无报错

**Comment by day-xue** [comment]
有没有可能是图片问题

**Comment by day-xue** [comment]
我用的没问题
