### ISSUE TITLE
✨ [Feature]: Dialog组件函数调用时如何手动关闭？确定和取消按钮需要自定义

### ISSUE THREAD

**Issue by wp1016** [3lang3/react-vant#672]
### What is the new or updated feature that you are suggesting?

Dialog组件函数调用时无法手动关闭

### Why should this feature be included?

Dialog组件提供关闭方法

**Comment by 3lang3** [comment]
onConfirm和onClose不行吗

**Comment by wp1016** [comment]
Dialog.onClose()吗？

**Comment by 3lang3** [comment]
```tsx
Dialog.confirm({
            title: '标题',
            message: '代码是写出来给人看的，附带能在机器上运行',
            onCancel: () => console.log('cancel'),
            onConfirm: () => console.log('confirm')
})
```

如果希望外部组件控制，请参照[组件调用](http://localhost:4000/components/dialog#%E7%BB%84%E4%BB%B6%E8%B0%83%E7%94%A8)
