### ISSUE TITLE
🐛 [Bug]: ShareSheet 在控制台报错

### ISSUE THREAD

**Issue by MoneySacon** [3lang3/react-vant#677]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3

### Descripition

![image](https://github.com/3lang3/react-vant/assets/144115695/0c5bd103-423b-4cdf-9028-3be9fcc7d377)

**Comment by light212** [comment]
我也是相同的问题，看了下问题所在
没有传入duration属性就会报错
把这个加上就ok了
duration={300}

**Comment by MoneySacon** [comment]
> 

好的，谢谢可以了

**Comment by light212** [comment]
不客气
