### ISSUE TITLE
[Doc Bug]

### ISSUE THREAD

**Issue by feifanshijie** [3lang3/react-vant#68]
Overlay 遮罩层
示例组件名字
**Screensh**
![@D1}2FB7KR4U4SW54`F`_DY](https://user-images.githubusercontent.com/12168991/133181922-a1bf6fb7-7d6d-4a57-94aa-75e4f2350eba.png)
ots

**Comment by 3lang3** [comment]
fix by 1e1156fafdc7da749dbed6eb4fb354af14c02fb0

**Comment by 3lang3** [comment]
@all-contributors please add @feifanshijie  bug
