### ISSUE TITLE
🐛 [Bug]: area组件 报错

### ISSUE THREAD

**Issue by juzhiqiang** [3lang3/react-vant#685]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.31

### Descripition

![image](https://github.com/3lang3/react-vant/assets/25214312/5e1c1362-fe5a-4bf4-b1b3-92106c274c32)

**Comment by 3lang3** [comment]
3.3.2已修复
