### ISSUE TITLE
[Bug:Tabs]IntersectionObserver is not defined

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#69]
**Describe the bug**
next 中使用 Tabs 组件的 `renderTitle` API时报错
`IntersectionObserver is not defined`

**To Reproduce**
有可能是第一次不报错，刷新一下就报错了
```jsx
<Tabs active={2} sticky>
          {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13].map((item) => (
            <Tabs.TabPane key={item} renderTitle={"12314"}>
              <div style={{ height: '100vh' }}>内容 {item}</div>
            </Tabs.TabPane>
          ))}
        </Tabs>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/33956589/133190252-8d5a0f69-82b9-4e2f-a4a8-5dc2bdadb620.png)

**Comment by 3lang3** [comment]
@TinsFox 最新版的0.5.7已修复。

**Comment by 3lang3** [comment]
#66
