### ISSUE TITLE
🐛 [Bug]: [type error] Calendar value type error

### ISSUE THREAD

**Issue by Shunjun** [3lang3/react-vant#693]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

18.2.0

### Descripition

The Calendar value type is Incompatible with the document
![CleanShot 2023-12-18 at 11 18 39@2x](https://github.com/3lang3/react-vant/assets/10445938/462d7023-0b92-4db8-ad27-b949fc4a48cb)
![CleanShot 2023-12-18 at 11 20 12@2x](https://github.com/3lang3/react-vant/assets/10445938/af4c432c-b19f-4711-9d78-0259e93be7ab)

**Comment by day-xue** [comment]
给个默认值 undefined

**Comment by Shunjun** [comment]
undefined 无法将有值的组件置为空值
