### ISSUE TITLE
你好sku组件不支持手动关闭吗🐛 [Bug]: 

### ISSUE THREAD

**Issue by chaochaoer** [3lang3/react-vant#698]
### Which React Vant packages are impacted?

- [x] `react-vant` (React Vant core)
- [x] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.3.0

### Descripition

我使用sku组件，使用提供的show方法打开组件，但是我该怎么关闭呢，比如我选完产品规格之后点击购买，这个时候sku组件无法手动关闭sku组件，并且我看源码里面好像也没有提供相关的方法暴露给上层，感谢！

**Comment by 3lang3** [comment]
可以设置 `resetOnHide` 属性，然后调用组件实例的 `reset()` 方法
