### ISSUE TITLE
🐛 [Bug]: ImagePreview.open({ images})，函数传参images，图片无法显示

### ISSUE THREAD

**Issue by zhengujiang** [3lang3/react-vant#699]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

V3.3.2

### Descripition

使用ImagePreview组件时，ImagePreview.open({ images})，images通过函数传参的方式传递，图片无法显示

**Comment by 3lang3** [comment]
images只支持数组字符串 `string[]`
