### ISSUE TITLE
🐛 [Bug]: Uploader defaultValue值清空后组件仍然显示图片

### ISSUE THREAD

**Issue by LOADINGG** [3lang3/react-vant#700]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

^3.3.1

### Descripition

数据提交给后台后，期望清空Uploader，defaultValue值设置为[]，图片展示列表还在，要怎么清空？

**Comment by 3lang3** [comment]
@LOADINGG defaultValue只会再组件mount时起作用(响应)，建议使用value
