### ISSUE TITLE
🐛 [Bug]: Calendar 日期区间选择问题

### ISSUE THREAD

**Issue by LOADINGG** [3lang3/react-vant#705]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

^3.3.1

### Descripition

Calendar 做日期区间选择，绑定onSelect事件，会默认自己选择节日日期到当日。
![日历](https://github.com/3lang3/react-vant/assets/6230922/0fb7bbb1-8727-4f1a-aaa1-3a65c7bb1f5b)

**Comment by 3lang3** [comment]
无法复现，方便提供最小复现代码demo吗

**Comment by LOADINGG** [comment]
` const [date, setDate] = useState('2014-03-01~2024-03-15')

  const dateConfirm = (e) => {
    setDate(`${dayjs(e[0]).format('YYYY-MM-DD')}~${dayjs(e[1]).format('YYYY-MM-DD')}`)
  }

  return (
    <div>
    	<p>已选择的时间：{date}</p>
      <Calendar
		visible={true}
		type='range'
		minDate={new Date('2014/03/01')}
		maxDate={new Date()}
		color="#2D83E8"
		onSelect={(e) => dateConfirm(e)}
		showConfirm={false}
		maxRange={31}
    >
	</Calendar>
    </div>
  );`

**Comment by LOADINGG** [comment]
`const [date, setDate] = useState('2014-03-01~2024-03-15')

const dateConfirm = (e) => {
setDate(${dayjs(e[0]).format('YYYY-MM-DD')}~${dayjs(e[1]).format('YYYY-MM-DD')})
}

return (
	<>
		<span>已选择的时间：{date}</span>

		<Calendar
			visible={true}
			type='range'
			minDate={new Date('2014/03/01')}
			maxDate={new Date()}
			color="#2D83E8"
			onSelect={(e) => dateConfirm(e)}
			showConfirm={false}
			maxRange={31}
		></Calendar>
	</>
);`

**Comment by 3lang3** [comment]
```jsx
const today = new Date()
const tommorow = new Date(today.getTime() + 24 * 60 * 60 * 1000)

const [date, setDate] = useState([today, tommorow])

return (
<Calendar type='range' value={value} onSelect={(v) => setValue(v)} />
)
```
