### ISSUE TITLE
🐛 [Bug]: The doc can't switch to english

### ISSUE THREAD

**Issue by 13RTK** [3lang3/react-vant#707]
### Which React Vant packages are impacted?

- [ ] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.3.4

### Descripition

![image](https://github.com/3lang3/react-vant/assets/63441399/8b1ebc63-55b4-4233-8986-c8b5835da2c6)

**Comment by 3lang3** [comment]
抱歉 暂时没精力支持en
