### ISSUE TITLE
[docs] nav 排序

### ISSUE THREAD

**Issue by TinsFox** [3lang3/react-vant#79]
**Is your feature request related to a problem? Please describe.**

文档左侧的导航根据组件的首字母排序，可以方便定位组件

**Describe the solution you'd like**

在文档的cli中增加排序方法

**Describe alternatives you've considered**

在文档启动前调用排序方法将组件目录排序后的数据重写`vant.config.js`

**Comment by 3lang3** [comment]
close by #81
