### ISSUE TITLE
[BUG] Tabs 的actived bug

### ISSUE THREAD

**Issue by mytheart** [3lang3/react-vant#90]
1. Tabs 的actived 有值时，偶尔不能默认选中，且即使选中了但内容区没有滚动到相应位置；
2. 改变Tabs的actived值，没有任何作用；
3. 当Tabs的左后一个tab高度不足时，此时滚动到最底部不会选中最后一个tab

**Comment by 3lang3** [comment]
close by aada5e3afdde7d4fc701da2e91171ee317937f3a
